// ─────────────────────────────────────────────────────────────────────────────
// gradeCardData.js
// Canonical data model and resolver functions for Student Grade Card & Transcript Portal
// ─────────────────────────────────────────────────────────────────────────────

export const STUDENT_PROFILE = {
  id: "student-1",
  name: "Hamid Rza",
  usn: "1MS22CS089",
  rollNumber: "CS22B042",
  degree: "Bachelor of Technology (B.Tech)",
  branch: "Computer Science & Engineering",
  department: "Department of Computer Science & Engineering",
  batch: "2022 – 2026",
  admissionYear: "2022",
  college: "XYZ College of Engineering, Mumbai",
  university: "State Technological University",
  currentSemester: 7,
  academicYear: "2025–26",
  cumulativeCGPA: 8.24,
  cumulativeCreditsEarned: 142,
  cumulativeCreditsRequired: 160,
  cumulativeCreditsAttempted: 144,
  academicStanding: "Good Standing",
  standingDescription:
    "Student meets all cumulative GPA, continuous assessment, and minimum semester progression requirements with no active disciplinary holds.",
  avatar: "/assets/profile/avatar.jpg",
};

export const GRADE_SCALE = [
  {
    grade: "O",
    gradePoint: 10,
    label: "Outstanding",
    range: "90% – 100%",
    description: "Exceptional mastery of subject content and practical application.",
    badgeClass: "bg-emerald-100 dark:bg-emerald-950/70 text-emerald-800 dark:text-emerald-300 border-emerald-300 dark:border-emerald-800",
  },
  {
    grade: "A+",
    gradePoint: 9,
    label: "Excellent",
    range: "80% – 89%",
    description: "High command of concepts with thorough analytical accuracy.",
    badgeClass: "bg-emerald-50 dark:bg-emerald-950/50 text-emerald-700 dark:text-emerald-300 border-emerald-200 dark:border-emerald-800/80",
  },
  {
    grade: "A",
    gradePoint: 8,
    label: "Very Good",
    range: "70% – 79%",
    description: "Solid conceptual proficiency and above-standard problem resolution.",
    badgeClass: "bg-teal-50 dark:bg-teal-950/50 text-teal-700 dark:text-teal-300 border-teal-200 dark:border-teal-800",
  },
  {
    grade: "B+",
    gradePoint: 7,
    label: "Good",
    range: "60% – 69%",
    description: "Satisfactory competence in standard domain methodologies.",
    badgeClass: "bg-cyan-50 dark:bg-cyan-950/50 text-cyan-700 dark:text-cyan-300 border-cyan-200 dark:border-cyan-800",
  },
  {
    grade: "B",
    gradePoint: 6,
    label: "Above Average",
    range: "50% – 59%",
    description: "Basic comprehension meeting institutional benchmarks.",
    badgeClass: "bg-amber-50 dark:bg-amber-950/50 text-amber-700 dark:text-amber-300 border-amber-200 dark:border-amber-800",
  },
  {
    grade: "C",
    gradePoint: 5,
    label: "Average / Pass",
    range: "40% – 49%",
    description: "Minimum qualifying credit threshold fulfilled.",
    badgeClass: "bg-amber-100 dark:bg-amber-900/30 text-amber-800 dark:text-amber-300 border-amber-300 dark:border-amber-700",
  },
  {
    grade: "F",
    gradePoint: 0,
    label: "Fail",
    range: "Below 40%",
    description: "Inadequate assessment performance; credit not accrued.",
    badgeClass: "bg-rose-100 dark:bg-rose-950/60 text-rose-800 dark:text-rose-300 border-rose-300 dark:border-rose-800",
  },
  {
    grade: "I",
    gradePoint: 0,
    label: "Incomplete",
    range: "Pending",
    description: "Evaluation deferred pending viva, practical exam or medical leave.",
    badgeClass: "bg-purple-100 dark:bg-purple-950/50 text-purple-800 dark:text-purple-300 border-purple-300 dark:border-purple-800",
  },
  {
    grade: "W",
    gradePoint: 0,
    label: "Withheld",
    range: "Administrative",
    description: "Result withheld for document or administrative verification.",
    badgeClass: "bg-gray-100 dark:bg-gray-800 text-gray-700 dark:text-gray-300 border-gray-300 dark:border-gray-700",
  },
];

export const SEMESTER_DATA = [
  {
    id: "sem-1",
    number: 1,
    label: "Semester I",
    shortLabel: "Sem 1",
    academicYear: "2022–23",
    term: "Autumn Session (Odd)",
    status: "Completed",
    isPublished: true,
    isCurrent: false,
    sgpa: 7.10,
    previousSgpa: null,
    cgpaAfterSem: 7.10,
    creditsRegistered: 20,
    creditsEarned: 20,
    creditsRemaining: 0,
    publishedDate: "18 Jan 2023",
    resultNotice: "End-semester examination results officially ratified by the Academic Board.",
    subjects: [
      {
        code: "MAT-101",
        slug: "MAT-101",
        name: "Engineering Mathematics I",
        credits: 4,
        internal: 38,
        external: 42,
        total: 80,
        grade: "A+",
        gradePoint: 9,
        status: "Passed",
        marksBreakdown: [
          { component: "Continuous Assessment 1", max: 25, scored: 23 },
          { component: "Continuous Assessment 2", max: 25, scored: 24 },
          { component: "Tutorial Submissions", max: 10, scored: 9 },
          { component: "End-Semester University Exam", max: 50, scored: 42 },
        ],
        remarks: "Exceptional calculus and differential equation solving skills.",
      },
      {
        code: "PHY-101",
        slug: "PHY-101",
        name: "Engineering Physics",
        credits: 4,
        internal: 34,
        external: 36,
        total: 70,
        grade: "A",
        gradePoint: 8,
        status: "Passed",
        marksBreakdown: [
          { component: "Mid-Term Test", max: 25, scored: 20 },
          { component: "Quizzes & Homework", max: 15, scored: 14 },
          { component: "End-Semester Written Exam", max: 60, scored: 44 },
        ],
        remarks: "Solid grasp of quantum physics and optics.",
      },
      {
        code: "EE-101",
        slug: "EE-101",
        name: "Basic Electrical & Electronics",
        credits: 3,
        internal: 32,
        external: 35,
        total: 67,
        grade: "B+",
        gradePoint: 7,
        status: "Passed",
        marksBreakdown: [
          { component: "Internal Test 1", max: 20, scored: 15 },
          { component: "Internal Test 2", max: 20, scored: 17 },
          { component: "Semester End Exam", max: 60, scored: 35 },
        ],
        remarks: "Good comprehension of AC circuit theorems.",
      },
      {
        code: "ME-102",
        slug: "ME-102",
        name: "Engineering Graphics & CAD",
        credits: 3,
        internal: 30,
        external: 32,
        total: 62,
        grade: "B+",
        gradePoint: 7,
        status: "Passed",
        marksBreakdown: [
          { component: "AutoCAD Lab Sheets", max: 30, scored: 26 },
          { component: "Mid-Term Practical Test", max: 20, scored: 16 },
          { component: "Final Drawing Submission", max: 50, scored: 36 },
        ],
        remarks: "Consistent orthographic projection sheet submissions.",
      },
      {
        code: "CSE-100",
        slug: "CSE-100",
        name: "Programming in C",
        credits: 4,
        internal: 36,
        external: 40,
        total: 76,
        grade: "A",
        gradePoint: 8,
        status: "Passed",
        marksBreakdown: [
          { component: "Lab Coding Assessments", max: 25, scored: 22 },
          { component: "Theory Tests", max: 25, scored: 20 },
          { component: "End-Term Theory Exam", max: 50, scored: 40 },
        ],
        remarks: "Strong proficiency in pointers and memory manipulation.",
      },
      {
        code: "LAB-101",
        slug: "LAB-101",
        name: "Physics & Computing Laboratory",
        credits: 2,
        internal: 23,
        external: 24,
        total: 47,
        grade: "A",
        gradePoint: 8,
        status: "Passed",
        marksBreakdown: [
          { component: "Continuous Lab Work", max: 25, scored: 23 },
          { component: "Practical Exam & Viva", max: 25, scored: 24 },
        ],
        remarks: "Timely completion of experimental observations.",
      },
    ],
  },
  {
    id: "sem-2",
    number: 2,
    label: "Semester II",
    shortLabel: "Sem 2",
    academicYear: "2022–23",
    term: "Spring Session (Even)",
    status: "Completed",
    isPublished: true,
    isCurrent: false,
    sgpa: 7.40,
    previousSgpa: 7.10,
    cgpaAfterSem: 7.25,
    creditsRegistered: 20,
    creditsEarned: 20,
    creditsRemaining: 0,
    publishedDate: "24 Jun 2023",
    resultNotice: "Official semester results released without any discrepancy or withheld grades.",
    subjects: [
      {
        code: "MAT-201",
        slug: "MAT-201",
        name: "Engineering Mathematics II",
        credits: 4,
        internal: 36,
        external: 40,
        total: 76,
        grade: "A",
        gradePoint: 8,
        status: "Passed",
        marksBreakdown: [
          { component: "Assessment 1", max: 25, scored: 21 },
          { component: "Assessment 2", max: 25, scored: 22 },
          { component: "End-Semester Exam", max: 50, scored: 40 },
        ],
        remarks: "Good command over Laplace transforms and complex numbers.",
      },
      {
        code: "CHM-101",
        slug: "CHM-101",
        name: "Engineering Chemistry",
        credits: 4,
        internal: 34,
        external: 38,
        total: 72,
        grade: "A",
        gradePoint: 8,
        status: "Passed",
        marksBreakdown: [
          { component: "Internal Evaluation", max: 40, scored: 34 },
          { component: "End-Semester Exam", max: 60, scored: 38 },
        ],
        remarks: "Thorough understanding of polymers and electrochemistry.",
      },
      {
        code: "ECE-101",
        slug: "ECE-101",
        name: "Basic Electronics & Digital Circuits",
        credits: 3,
        internal: 32,
        external: 36,
        total: 68,
        grade: "B+",
        gradePoint: 7,
        status: "Passed",
        marksBreakdown: [
          { component: "Class Tests", max: 30, scored: 23 },
          { component: "End-Semester Exam", max: 70, scored: 45 },
        ],
        remarks: "Capable in transistor biasing and logic gates.",
      },
      {
        code: "ME-103",
        slug: "ME-103",
        name: "Elements of Mechanical Engineering",
        credits: 3,
        internal: 30,
        external: 34,
        total: 64,
        grade: "B+",
        gradePoint: 7,
        status: "Passed",
        marksBreakdown: [
          { component: "Internal Assignments", max: 30, scored: 23 },
          { component: "End-Semester Exam", max: 70, scored: 41 },
        ],
        remarks: "Satisfactory grasp of thermodynamics principles.",
      },
      {
        code: "CSE-102",
        slug: "CSE-102",
        name: "Object-Oriented Programming (C++)",
        credits: 4,
        internal: 40,
        external: 45,
        total: 85,
        grade: "A+",
        gradePoint: 9,
        status: "Passed",
        marksBreakdown: [
          { component: "OOP Lab Tasks", max: 30, scored: 28 },
          { component: "Mid-Term Test", max: 20, scored: 19 },
          { component: "End-Semester Written Exam", max: 50, scored: 45 },
        ],
        remarks: "Outstanding understanding of inheritance and polymorphism.",
      },
      {
        code: "LAB-102",
        slug: "LAB-102",
        name: "Digital Workshop & OOP Lab",
        credits: 2,
        internal: 22,
        external: 25,
        total: 47,
        grade: "A+",
        gradePoint: 9,
        status: "Passed",
        marksBreakdown: [
          { component: "Practical Records", max: 25, scored: 22 },
          { component: "External Viva-Voce", max: 25, scored: 25 },
        ],
        remarks: "High-scoring viva on design patterns and STL.",
      },
    ],
  },
  {
    id: "sem-3",
    number: 3,
    label: "Semester III",
    shortLabel: "Sem 3",
    academicYear: "2023–24",
    term: "Autumn Session (Odd)",
    status: "Completed",
    isPublished: true,
    isCurrent: false,
    sgpa: 7.80,
    previousSgpa: 7.40,
    cgpaAfterSem: 7.44,
    creditsRegistered: 22,
    creditsEarned: 22,
    creditsRemaining: 0,
    publishedDate: "22 Jan 2024",
    resultNotice: "Core departmental course grading confirmed. No backlogs reported.",
    subjects: [
      {
        code: "MAT-301",
        slug: "MAT-301",
        name: "Discrete Mathematics & Graph Theory",
        credits: 4,
        internal: 38,
        external: 44,
        total: 82,
        grade: "A+",
        gradePoint: 9,
        status: "Passed",
        marksBreakdown: [
          { component: "IA-1 & Quizzes", max: 25, scored: 23 },
          { component: "IA-2", max: 25, scored: 22 },
          { component: "University Exam", max: 50, scored: 44 },
        ],
        remarks: "Excellent grasp of combinatorics and planar graphs.",
      },
      {
        code: "CSE-201",
        slug: "CSE-201",
        name: "Data Structures & File Structures",
        credits: 4,
        internal: 42,
        external: 46,
        total: 88,
        grade: "A+",
        gradePoint: 9,
        status: "Passed",
        marksBreakdown: [
          { component: "Internal Assessment", max: 40, scored: 37 },
          { component: "Lab Coding Assessment", max: 20, scored: 19 },
          { component: "End-Semester Exam", max: 50, scored: 46 },
        ],
        remarks: "Exceptional tree traversal and balancing implementations.",
      },
      {
        code: "CSE-203",
        slug: "CSE-203",
        name: "Digital Logic & Computer Design",
        credits: 4,
        internal: 35,
        external: 38,
        total: 73,
        grade: "A",
        gradePoint: 8,
        status: "Passed",
        marksBreakdown: [
          { component: "Mid-Term", max: 30, scored: 25 },
          { component: "End-Semester Exam", max: 70, scored: 48 },
        ],
        remarks: "Clean Karnaugh map minimization and sequential circuit design.",
      },
      {
        code: "CSE-205",
        slug: "CSE-205",
        name: "Computer Organization & Architecture",
        credits: 4,
        internal: 33,
        external: 37,
        total: 70,
        grade: "A",
        gradePoint: 8,
        status: "Passed",
        marksBreakdown: [
          { component: "Assessments", max: 30, scored: 24 },
          { component: "End-Semester Exam", max: 70, scored: 46 },
        ],
        remarks: "Good understanding of pipelining and cache mapping.",
      },
      {
        code: "CSE-207",
        slug: "CSE-207",
        name: "Principles of Programming Languages",
        credits: 3,
        internal: 31,
        external: 34,
        total: 65,
        grade: "B+",
        gradePoint: 7,
        status: "Passed",
        marksBreakdown: [
          { component: "Assignments & Term Paper", max: 30, scored: 23 },
          { component: "End-Semester Exam", max: 70, scored: 42 },
        ],
        remarks: "Solid comparison between functional and imperative paradigms.",
      },
      {
        code: "LAB-201",
        slug: "LAB-201",
        name: "Data Structures Lab",
        credits: 2,
        internal: 24,
        external: 25,
        total: 49,
        grade: "O",
        gradePoint: 10,
        status: "Passed",
        marksBreakdown: [
          { component: "Lab Journal & Execution", max: 25, scored: 24 },
          { component: "External Practical Exam", max: 25, scored: 25 },
        ],
        remarks: "Flawless code execution and documentation in lab finals.",
      },
      {
        code: "LAB-203",
        slug: "LAB-203",
        name: "Digital Electronics Lab",
        credits: 1,
        internal: 22,
        external: 23,
        total: 45,
        grade: "A+",
        gradePoint: 9,
        status: "Passed",
        marksBreakdown: [
          { component: "Continuous Assessment", max: 25, scored: 22 },
          { component: "Final Viva", max: 25, scored: 23 },
        ],
        remarks: "Accurate circuit breadboard assembly.",
      },
    ],
  },
  {
    id: "sem-4",
    number: 4,
    label: "Semester IV",
    shortLabel: "Sem 4",
    academicYear: "2023–24",
    term: "Spring Session (Even)",
    status: "Completed",
    isPublished: true,
    isCurrent: false,
    sgpa: 8.00,
    previousSgpa: 7.80,
    cgpaAfterSem: 7.59,
    creditsRegistered: 22,
    creditsEarned: 22,
    creditsRemaining: 0,
    publishedDate: "28 Jun 2024",
    resultNotice: "Semester IV results ratified. Student entered Top 15th percentile of CSE batch.",
    subjects: [
      {
        code: "CSE-202",
        slug: "CSE-202",
        name: "Design & Analysis of Algorithms",
        credits: 4,
        internal: 41,
        external: 47,
        total: 88,
        grade: "A+",
        gradePoint: 9,
        status: "Passed",
        marksBreakdown: [
          { component: "Internal Assessments", max: 40, scored: 37 },
          { component: "Dynamic Programming Project", max: 10, scored: 9.5 },
          { component: "End-Semester Exam", max: 50, scored: 47 },
        ],
        remarks: "Deep understanding of amortized analysis and greedy strategies.",
      },
      {
        code: "CSE-204",
        slug: "CSE-204",
        name: "Operating Systems & Systems Programming",
        credits: 4,
        internal: 38,
        external: 43,
        total: 81,
        grade: "A+",
        gradePoint: 9,
        status: "Passed",
        marksBreakdown: [
          { component: "Continuous Assessments", max: 30, scored: 27 },
          { component: "Process Synchronization Lab", max: 20, scored: 18 },
          { component: "End-Semester Exam", max: 50, scored: 43 },
        ],
        remarks: "Well-reasoned deadlocks handling and virtual memory models.",
      },
      {
        code: "CSE-206",
        slug: "CSE-206",
        name: "Theory of Computation & Automata",
        credits: 4,
        internal: 34,
        external: 38,
        total: 72,
        grade: "A",
        gradePoint: 8,
        status: "Passed",
        marksBreakdown: [
          { component: "Internal Assessment", max: 30, scored: 24 },
          { component: "Turing Machine Assignment", max: 10, scored: 9 },
          { component: "End-Semester Exam", max: 60, scored: 45 },
        ],
        remarks: "Good construction of context-free grammars and pushdown automata.",
      },
      {
        code: "CSE-208",
        slug: "CSE-208",
        name: "Microprocessors & Interfacing",
        credits: 3,
        internal: 32,
        external: 36,
        total: 68,
        grade: "B+",
        gradePoint: 7,
        status: "Passed",
        marksBreakdown: [
          { component: "Internal Assessment", max: 30, scored: 23 },
          { component: "Assembly Assignment", max: 10, scored: 8.5 },
          { component: "End-Semester Exam", max: 60, scored: 36.5 },
        ],
        remarks: "Clean 8086 assembly programming and interrupt handling.",
      },
      {
        code: "ENV-201",
        slug: "ENV-201",
        name: "Environmental Studies & Sustainability",
        credits: 2,
        internal: 42,
        external: 44,
        total: 86,
        grade: "A+",
        gradePoint: 9,
        status: "Passed",
        marksBreakdown: [
          { component: "Field Report", max: 30, scored: 28 },
          { component: "Term Paper", max: 20, scored: 19 },
          { component: "End-Semester Quiz", max: 50, scored: 44 },
        ],
        remarks: "Detailed submission on renewable energy consumption in data centers.",
      },
      {
        code: "LAB-202",
        slug: "LAB-202",
        name: "Algorithms & OS Laboratory",
        credits: 3,
        internal: 24,
        external: 25,
        total: 49,
        grade: "O",
        gradePoint: 10,
        status: "Passed",
        marksBreakdown: [
          { component: "Continuous Execution", max: 25, scored: 24 },
          { component: "Final Lab Practical Exam", max: 25, scored: 25 },
        ],
        remarks: "Flawless UNIX shell scripting and multi-threaded semaphore demos.",
      },
      {
        code: "LAB-204",
        slug: "LAB-204",
        name: "Microprocessor Laboratory",
        credits: 2,
        internal: 22,
        external: 23,
        total: 45,
        grade: "A+",
        gradePoint: 9,
        status: "Passed",
        marksBreakdown: [
          { component: "Continuous Lab Experiments", max: 25, scored: 22 },
          { component: "Viva & Testing", max: 25, scored: 23 },
        ],
        remarks: "Accurate stepper motor and DAC interface configurations.",
      },
    ],
  },
  {
    id: "sem-5",
    number: 5,
    label: "Semester V",
    shortLabel: "Sem 5",
    academicYear: "2024–25",
    term: "Autumn Session (Odd)",
    status: "Completed",
    isPublished: true,
    isCurrent: false,
    sgpa: 8.20,
    previousSgpa: 8.00,
    cgpaAfterSem: 7.73,
    creditsRegistered: 24,
    creditsEarned: 24,
    creditsRemaining: 0,
    publishedDate: "25 Jan 2025",
    resultNotice: "Results published without discrepancy. Strong performance in systems and database design.",
    subjects: [
      {
        code: "CSE-301",
        slug: "CSE-302-dbms",
        name: "Database Management Systems",
        credits: 4,
        internal: 42,
        external: 46,
        total: 88,
        grade: "A+",
        gradePoint: 9,
        status: "Passed",
        marksBreakdown: [
          { component: "IA-1 (Relational Algebra & SQL)", max: 20, scored: 19 },
          { component: "IA-2 (Indexing & B-Trees)", max: 20, scored: 18 },
          { component: "Course Database Project", max: 10, scored: 9.5 },
          { component: "End-Semester University Exam", max: 50, scored: 46 },
        ],
        remarks: "Superior design of 3NF database schema and query tuning.",
      },
      {
        code: "CSE-303",
        slug: "CSE-303",
        name: "Computer Networks & Protocols",
        credits: 4,
        internal: 39,
        external: 44,
        total: 83,
        grade: "A+",
        gradePoint: 9,
        status: "Passed",
        marksBreakdown: [
          { component: "Mid-Term", max: 30, scored: 26 },
          { component: "Socket Programming Project", max: 20, scored: 18 },
          { component: "End-Semester Exam", max: 50, scored: 44 },
        ],
        remarks: "In-depth understanding of TCP sliding window and BGP routing.",
      },
      {
        code: "CSE-305",
        slug: "CSE-305",
        name: "Software Engineering & Agile Methodologies",
        credits: 4,
        internal: 36,
        external: 40,
        total: 76,
        grade: "A",
        gradePoint: 8,
        status: "Passed",
        marksBreakdown: [
          { component: "Scrum Team Sprint Artifacts", max: 30, scored: 27 },
          { component: "End-Semester Written Exam", max: 70, scored: 49 },
        ],
        remarks: "Diligent test-driven design documentation and user story formulation.",
      },
      {
        code: "CSE-307",
        slug: "CSE-307",
        name: "Formal Methods & Verification",
        credits: 3,
        internal: 33,
        external: 37,
        total: 70,
        grade: "A",
        gradePoint: 8,
        status: "Passed",
        marksBreakdown: [
          { component: "Internal Quizzes", max: 30, scored: 23 },
          { component: "End-Semester Exam", max: 70, scored: 47 },
        ],
        remarks: "Competent proof formulation using temporal logic.",
      },
      {
        code: "HSS-301",
        slug: "HSS-301",
        name: "Professional Ethics & Cyber Law",
        credits: 2,
        internal: 40,
        external: 42,
        total: 82,
        grade: "A+",
        gradePoint: 9,
        status: "Passed",
        marksBreakdown: [
          { component: "Case Study Presentation", max: 30, scored: 27 },
          { component: "Written Exam", max: 70, scored: 55 },
        ],
        remarks: "Comprehensive analysis of GDPR regulations and IP frameworks.",
      },
      {
        code: "LAB-301",
        slug: "Lab-2",
        name: "DBMS & Networks Laboratory",
        credits: 4,
        internal: 24,
        external: 25,
        total: 49,
        grade: "O",
        gradePoint: 10,
        status: "Passed",
        marksBreakdown: [
          { component: "Continuous Assessment", max: 25, scored: 24 },
          { component: "Practical Lab Examination", max: 25, scored: 25 },
        ],
        remarks: "Excellent demonstration of stored procedures and packet sniffers.",
      },
      {
        code: "PROJ-301",
        slug: "PROJ-301",
        name: "Mini Project — Domain Application",
        credits: 3,
        internal: 44,
        external: 47,
        total: 91,
        grade: "O",
        gradePoint: 10,
        status: "Passed",
        marksBreakdown: [
          { component: "System Architecture Review", max: 30, scored: 29 },
          { component: "Live Product Demonstration", max: 40, scored: 38 },
          { component: "Technical Code Audit", max: 30, scored: 28 },
        ],
        remarks: "Built an open-source campus resource coordinator with high praise from faculty committee.",
      },
    ],
  },
  {
    id: "sem-6",
    number: 6,
    label: "Semester VI",
    shortLabel: "Sem 6",
    academicYear: "2024–25",
    term: "Spring Session (Even)",
    status: "Completed",
    isPublished: true,
    isCurrent: false,
    sgpa: 8.10,
    previousSgpa: 8.20,
    cgpaAfterSem: 7.80,
    creditsRegistered: 24,
    creditsEarned: 24,
    creditsRemaining: 0,
    publishedDate: "30 Jun 2025",
    resultNotice: "Sixth semester grades formalized. Cumulative credits reached 132/160 required benchmark.",
    subjects: [
      {
        code: "CSE-304",
        slug: "CSE-304",
        name: "Compiler Design & Code Generation",
        credits: 4,
        internal: 37,
        external: 41,
        total: 78,
        grade: "A",
        gradePoint: 8,
        status: "Passed",
        marksBreakdown: [
          { component: "Lex / Yacc Parser Project", max: 25, scored: 22 },
          { component: "Mid-Term", max: 25, scored: 20 },
          { component: "End-Semester Exam", max: 50, scored: 41 },
        ],
        remarks: "Proficient in LL(1) parsing tables and intermediate code optimization.",
      },
      {
        code: "CSE-306",
        slug: "CSE-306",
        name: "Cloud Computing & Distributed Systems",
        credits: 4,
        internal: 42,
        external: 45,
        total: 87,
        grade: "A+",
        gradePoint: 9,
        status: "Passed",
        marksBreakdown: [
          { component: "Docker & Kubernetes Deployment", max: 30, scored: 29 },
          { component: "Mid-Term Exam", max: 20, scored: 18 },
          { component: "End-Semester Exam", max: 50, scored: 45 },
        ],
        remarks: "Exceptional architecture of fault-tolerant microservices.",
      },
      {
        code: "CSE-308",
        slug: "CSE-308",
        name: "Information & Network Security",
        credits: 4,
        internal: 36,
        external: 40,
        total: 76,
        grade: "A",
        gradePoint: 8,
        status: "Passed",
        marksBreakdown: [
          { component: "Cryptography Lab Assays", max: 25, scored: 22 },
          { component: "Continuous Assessment", max: 25, scored: 20 },
          { component: "End-Semester Exam", max: 50, scored: 40 },
        ],
        remarks: "Solid implementation of RSA encryption and digital certificates.",
      },
      {
        code: "CSE-310",
        slug: "CSE-310",
        name: "Machine Learning Foundations",
        credits: 3,
        internal: 40,
        external: 44,
        total: 84,
        grade: "A+",
        gradePoint: 9,
        status: "Passed",
        marksBreakdown: [
          { component: "Kaggle Model Competition", max: 30, scored: 28 },
          { component: "Mid-Term", max: 20, scored: 18 },
          { component: "End-Semester Exam", max: 50, scored: 44 },
        ],
        remarks: "High accuracy models with rigorous cross-validation.",
      },
      {
        code: "OEC-201",
        slug: "OEC-201",
        name: "Open Elective — Entrepreneurship & Finance",
        credits: 3,
        internal: 34,
        external: 38,
        total: 72,
        grade: "A",
        gradePoint: 8,
        status: "Passed",
        marksBreakdown: [
          { component: "Venture Pitch Deck", max: 30, scored: 26 },
          { component: "Financial Analysis Paper", max: 20, scored: 17 },
          { component: "Written Exam", max: 50, scored: 38 },
        ],
        remarks: "Strong unit economics modeling for SaaS startups.",
      },
      {
        code: "LAB-302",
        slug: "LAB-302",
        name: "Cloud & Network Security Laboratory",
        credits: 3,
        internal: 23,
        external: 25,
        total: 48,
        grade: "O",
        gradePoint: 10,
        status: "Passed",
        marksBreakdown: [
          { component: "Continuous Lab Assessment", max: 25, scored: 23 },
          { component: "External Practical & Viva", max: 25, scored: 25 },
        ],
        remarks: "Secured top marks in penetration testing and TLS configurations.",
      },
      {
        code: "SEM-301",
        slug: "SEM-301",
        name: "Research Seminar & Technical Paper",
        credits: 3,
        internal: 45,
        external: 46,
        total: 91,
        grade: "O",
        gradePoint: 10,
        status: "Passed",
        marksBreakdown: [
          { component: "Literature Survey", max: 30, scored: 29 },
          { component: "Conference Paper Submission", max: 40, scored: 39 },
          { component: "Oral Defense & Presentation", max: 30, scored: 29 },
        ],
        remarks: "Authored peer-reviewed paper on consensus protocols in private subnets.",
      },
    ],
  },
  {
    id: "sem-7",
    number: 7,
    label: "Semester VII",
    shortLabel: "Sem 7",
    academicYear: "2025–26",
    term: "Autumn Session (Odd)",
    status: "In Progress",
    isPublished: false,
    isCurrent: true,
    isProvisional: true,
    sgpa: 8.40,
    previousSgpa: 8.10,
    cgpaAfterSem: 8.24,
    creditsRegistered: 19,
    creditsEarned: 16,
    creditsRemaining: 3,
    publishedDate: "Provisional Internal Compilation (24 Sep 2026)",
    resultNotice:
      "Provisional internal assessment record. Continuous evaluations (IA-1, IA-2, Lab work) are compiled. Final university end-term examinations and elective grading are currently in progress.",
    subjects: [
      {
        code: "CSE-302",
        slug: "CSE-302-dsa",
        name: "Data Structures & Algorithms",
        credits: 4,
        internal: 38,
        external: 46,
        total: 84,
        grade: "A",
        gradePoint: 8,
        status: "Passed",
        marksBreakdown: [
          { component: "Internal Assessment 1 (IA-1)", max: 20, scored: 18 },
          { component: "Internal Assessment 2 (IA-2)", max: 20, scored: 17 },
          { component: "Assignment & Lab Work", max: 10, scored: 9 },
          { component: "Seminar / Viva", max: 10, scored: 8 },
          { component: "End-Semester Theory Exam", max: 40, scored: 32 },
        ],
        remarks: "High proficiency in dynamic programming and graph shortest path algorithms.",
      },
      {
        code: "CSE-101",
        slug: "CSE-101",
        name: "Web Development",
        credits: 4,
        internal: 39,
        external: 48,
        total: 87,
        grade: "A+",
        gradePoint: 9,
        status: "Passed",
        marksBreakdown: [
          { component: "IA-1 (Client Architecture)", max: 20, scored: 19 },
          { component: "IA-2 (Server APIs & Database)", max: 20, scored: 18 },
          { component: "Course Project & Code Review", max: 10, scored: 9.5 },
          { component: "Continuous Quizzes", max: 10, scored: 8.5 },
          { component: "End-Semester Practical Evaluation", max: 40, scored: 32 },
        ],
        remarks: "Exemplary production-grade React/Next.js application delivery.",
      },
      {
        code: "CSE-302",
        slug: "CSE-302-dbms",
        name: "Database Management Systems",
        credits: 4,
        internal: 36,
        external: 42,
        total: 78,
        grade: "A",
        gradePoint: 8,
        status: "Passed",
        marksBreakdown: [
          { component: "Internal Assessment 1", max: 20, scored: 17 },
          { component: "Internal Assessment 2", max: 20, scored: 16 },
          { component: "SQL Schema & Triggers", max: 10, scored: 9 },
          { component: "Concurrency Control Assignment", max: 10, scored: 8 },
          { component: "End-Semester Written Exam", max: 40, scored: 28 },
        ],
        remarks: "Solid theoretical understanding of ACID compliance and relational algebra.",
      },
      {
        code: "Lab-2",
        slug: "Lab-2",
        name: "Computer Networks Lab",
        credits: 2,
        internal: 24,
        external: 25,
        total: 49,
        grade: "O",
        gradePoint: 10,
        status: "Passed",
        marksBreakdown: [
          { component: "Packet Sniffing & Wireshark Assays", max: 15, scored: 14.5 },
          { component: "Socket Programming Lab Manual", max: 15, scored: 14.5 },
          { component: "Continuous Lab Performance", max: 10, scored: 10 },
          { component: "External Viva-Voce", max: 10, scored: 10 },
        ],
        remarks: "Outstanding execution in network packet inspection and TCP simulation.",
      },
      {
        code: "Lab-1",
        slug: "Lab-1",
        name: "Web Development Lab",
        credits: 2,
        internal: 23,
        external: 24,
        total: 47,
        grade: "A+",
        gradePoint: 9,
        status: "Passed",
        marksBreakdown: [
          { component: "Interactive Portfolio Sprint", max: 15, scored: 14 },
          { component: "Weekly Component Labs", max: 15, scored: 14 },
          { component: "Accessibility & Performance Audit", max: 10, scored: 9.5 },
          { component: "Viva & Code Walkthrough", max: 10, scored: 9.5 },
        ],
        remarks: "Demonstrated responsive design excellence and semantic HTML compliance.",
      },
      {
        code: "OEC-101",
        slug: "OEC-101",
        name: "Elective / Artificial Intelligence Foundations",
        credits: 3,
        internal: 34,
        external: 0,
        total: 34,
        grade: "I",
        gradePoint: 0,
        status: "Incomplete",
        marksBreakdown: [
          { component: "Internal Assessment 1 (IA-1)", max: 20, scored: 16 },
          { component: "Internal Assessment 2 (IA-2)", max: 20, scored: 15 },
          { component: "Mini Research Seminar", max: 10, scored: 8 },
          { component: "End-Semester Term Evaluation", max: 50, scored: null },
        ],
        remarks: "Term evaluation scheduled for next evaluation window. Credits pending final viva.",
      },
    ],
  },
  {
    id: "sem-8",
    number: 8,
    label: "Semester VIII",
    shortLabel: "Sem 8",
    academicYear: "2025–26",
    term: "Spring Session (Even)",
    status: "Result Pending",
    isPublished: false,
    isCurrent: false,
    sgpa: null,
    previousSgpa: 8.40,
    cgpaAfterSem: null,
    creditsRegistered: 18,
    creditsEarned: 0,
    creditsRemaining: 18,
    publishedDate: null,
    resultNotice:
      "Semester VIII academic registration, industry capstone internship, and major thesis defense commence in Spring 2026.",
    subjects: [
      {
        code: "CSE-401",
        slug: "CSE-401",
        name: "Major Capstone Project & Defense",
        credits: 10,
        internal: 0,
        external: 0,
        total: 0,
        grade: "I",
        gradePoint: 0,
        status: "Pending Result",
        marksBreakdown: [
          { component: "Phase 1 Architecture Defense", max: 25, scored: null },
          { component: "Phase 2 Implementation Milestone", max: 25, scored: null },
          { component: "Final Product Viva & Review", max: 50, scored: null },
        ],
        remarks: "Project synopsis submitted. Awaiting mid-term review committee schedule.",
      },
      {
        code: "CSE-403",
        slug: "CSE-403",
        name: "Industry Internship & Practice School",
        credits: 6,
        internal: 0,
        external: 0,
        total: 0,
        grade: "I",
        gradePoint: 0,
        status: "Pending Result",
        marksBreakdown: [
          { component: "Industry Mentor Evaluation", max: 50, scored: null },
          { component: "Faculty Coordinator Review", max: 50, scored: null },
        ],
        remarks: "Internship verification letter submitted to training & placement cell.",
      },
      {
        code: "CSE-405",
        slug: "CSE-405",
        name: "Advanced Distributed Systems",
        credits: 2,
        internal: 0,
        external: 0,
        total: 0,
        grade: "I",
        gradePoint: 0,
        status: "Pending Result",
        marksBreakdown: [
          { component: "Continuous Assessment", max: 40, scored: null },
          { component: "End-Semester Exam", max: 60, scored: null },
        ],
        remarks: "Classes scheduled to commence in January 2026.",
      },
    ],
  },
];

// Helper to fetch semester by id or number
export function getSemesterGradeCard(identifier) {
  if (!identifier) return SEMESTER_DATA.find((s) => s.isCurrent) || SEMESTER_DATA[6];
  if (typeof identifier === "number") {
    return SEMESTER_DATA.find((s) => s.number === identifier) || SEMESTER_DATA[6];
  }
  const found = SEMESTER_DATA.find(
    (s) => s.id === identifier || s.shortLabel.toLowerCase() === String(identifier).toLowerCase()
  );
  return found || SEMESTER_DATA[6];
}

// Compute dynamic stats for a given semester
export function calculateSemesterMetrics(sem) {
  if (!sem || !sem.subjects || sem.subjects.length === 0) {
    return {
      totalSubjects: 0,
      passedSubjects: 0,
      incompleteSubjects: 0,
      failedSubjects: 0,
      creditsRegistered: sem?.creditsRegistered || 0,
      creditsEarned: sem?.creditsEarned || 0,
      sgpa: sem?.sgpa || null,
      cgpa: sem?.cgpaAfterSem || null,
      weightedGradePoints: 0,
      totalCreditsForGpa: 0,
    };
  }

  let passedCount = 0;
  let incompleteCount = 0;
  let failedCount = 0;
  let totalCredits = 0;
  let earnedCredits = 0;
  let weightedPoints = 0;
  let gradedCredits = 0;

  sem.subjects.forEach((sub) => {
    totalCredits += sub.credits;
    if (sub.status === "Passed") {
      passedCount += 1;
      earnedCredits += sub.credits;
      weightedPoints += sub.gradePoint * sub.credits;
      gradedCredits += sub.credits;
    } else if (sub.status === "Incomplete" || sub.status === "Pending Result") {
      incompleteCount += 1;
    } else if (sub.status === "Failed") {
      failedCount += 1;
      gradedCredits += sub.credits;
    }
  });

  const calculatedSgpa = gradedCredits > 0 ? Number((weightedPoints / gradedCredits).toFixed(2)) : null;

  return {
    totalSubjects: sem.subjects.length,
    passedSubjects: passedCount,
    incompleteSubjects: incompleteCount,
    failedSubjects: failedCount,
    creditsRegistered: sem.creditsRegistered || totalCredits,
    creditsEarned: sem.creditsEarned !== undefined ? sem.creditsEarned : earnedCredits,
    sgpa: sem.sgpa !== null ? sem.sgpa : calculatedSgpa,
    cgpa: sem.cgpaAfterSem || null,
    weightedGradePoints: weightedPoints,
    totalCreditsForGpa: gradedCredits,
  };
}

// Full transcript records
export function getFullTranscript() {
  const publishedSemesters = SEMESTER_DATA.filter((s) => s.isPublished || s.isCurrent);
  const totalEarnedCredits = publishedSemesters.reduce((acc, sem) => acc + (sem.creditsEarned || 0), 0);
  const totalRegisteredCredits = publishedSemesters.reduce((acc, sem) => acc + (sem.creditsRegistered || 0), 0);

  return {
    student: STUDENT_PROFILE,
    semesters: SEMESTER_DATA,
    totalPublishedSemesters: publishedSemesters.length,
    totalEarnedCredits,
    totalRegisteredCredits,
    degreeCreditsRemaining: Math.max(0, STUDENT_PROFILE.cumulativeCreditsRequired - totalEarnedCredits),
    cumulativeCGPA: STUDENT_PROFILE.cumulativeCGPA,
    generationDate: "26 September 2026",
    documentId: "COS-TR-2026-8942",
    disclaimer:
      "This is a digital academic summary generated by College OS ERP for internal student advisory and semester review. For certified transcripts, apostilles, or degree certificates, please request an officially sealed document from the University Office of Examinations.",
  };
}
