// =============================================================================
// College OS - Internships & Hackathons Master Dataset
// Derived for: All, Internships, Hackathons, Open to All, Filters, Search, Pagination
// =============================================================================

export const OPPORTUNITY_TABS = [
  { id: "all", label: "All" },
  { id: "internships", label: "Internships" },
  { id: "hackathons", label: "Hackathons" },
  { id: "open-to-all", label: "Open to All" },
];

export const WORK_MODES = ["All", "Remote", "Hybrid", "On-site"];

export const LOCATIONS = ["All", "India", "Mumbai", "Remote", "Global"];

export const DURATIONS = ["All", "1–3 months", "3–6 months", "6+ months"];

export const ELIGIBILITIES = ["All", "All Students", "Selected Branches", "Selected Year", "Open to All"];

export const TOP_SKILLS = [
  "React",
  "Node.js",
  "Python",
  "Java",
  "DSA",
  "Machine Learning",
  "Data Structures",
  "TypeScript",
];

export const BADGE_STYLES = {
  Featured: {
    bg: "bg-emerald-50 dark:bg-emerald-950/50",
    text: "text-emerald-700 dark:text-emerald-300",
    border: "border-emerald-200/80 dark:border-emerald-800/50",
  },
  "High Demand": {
    bg: "bg-amber-50 dark:bg-amber-950/50",
    text: "text-amber-700 dark:text-amber-300",
    border: "border-amber-200/80 dark:border-amber-800/50",
  },
  Open: {
    bg: "bg-sky-50 dark:bg-sky-950/50",
    text: "text-sky-700 dark:text-sky-300",
    border: "border-sky-200/80 dark:border-sky-800/50",
  },
  "Limited Seats": {
    bg: "bg-purple-50 dark:bg-purple-950/50",
    text: "text-purple-700 dark:text-purple-300",
    border: "border-purple-200/80 dark:border-purple-800/50",
  },
  "Prize Pool": {
    bg: "bg-emerald-50 dark:bg-emerald-950/50",
    text: "text-emerald-700 dark:text-emerald-300",
    border: "border-emerald-200/80 dark:border-emerald-800/50",
  },
  Popular: {
    bg: "bg-amber-50 dark:bg-amber-950/50",
    text: "text-amber-700 dark:text-amber-300",
    border: "border-amber-200/80 dark:border-amber-800/50",
  },
  Trending: {
    bg: "bg-purple-50 dark:bg-purple-950/50",
    text: "text-purple-700 dark:text-purple-300",
    border: "border-purple-200/80 dark:border-purple-800/50",
  },
};

// =============================================================================
// Core Internships Dataset (Page 1: items 1-4, Page 2: items 5-8)
// =============================================================================
export const INITIAL_INTERNSHIPS = [
  {
    id: "intern-1",
    type: "internship",
    company: "Google",
    title: "Google STEP Internship",
    badge: "Featured",
    workMode: "Remote",
    location: "Remote / India",
    duration: "Dec 2025 – Feb 2026 (3 months)",
    durationCategory: "1–3 months",
    skills: ["Web Dev", "ML/AI", "DSA"],
    applications: "2.4k applied",
    applicationsCount: 2400,
    stipend: "₹65,000 / month",
    eligibility: "Open to 1st & 2nd year CS/IT students",
    openToAll: true,
    featured: true,
    saved: true,
    applied: false,
    logoType: "google",
    description:
      "The Student Training in Engineering Program (STEP) is a 12-week development internship focusing on practical software engineering, cloud infrastructure, and algorithmic problem solving under Google engineering mentorship.",
    requirements: [
      "Currently enrolled in a 1st or 2nd year undergraduate degree in Computer Science or related STEM field.",
      "Experience in one or more general-purpose programming languages: Python, Java, C++, or JavaScript.",
      "Demonstrated interest in learning scalable software development.",
    ],
    deadline: "15 Oct 2025",
  },
  {
    id: "intern-2",
    type: "internship",
    company: "Microsoft",
    title: "Microsoft Explore Internship",
    badge: "High Demand",
    workMode: "Remote / Hybrid",
    location: "Hyderabad / Bangalore",
    duration: "Jan 2026 – Apr 2026 (4 months)",
    durationCategory: "3–6 months",
    skills: ["Full Stack", "Cloud", "AI"],
    applications: "3.8k applied",
    applicationsCount: 3800,
    stipend: "₹80,000 / month",
    eligibility: "Open to 2nd & 3rd year engineering students",
    openToAll: true,
    featured: true,
    saved: false,
    applied: false,
    logoType: "microsoft",
    description:
      "Explore Microsoft is a 16-week rotational internship program allowing students to experience both Product Management and Software Engineering disciplines on Azure and Microsoft 365 cloud platforms.",
    requirements: [
      "Foundational understanding of data structures, web frameworks, and object-oriented programming.",
      "Enthusiasm for building developer tools, cloud microservices, and AI integrations.",
      "Collaborative mindset with strong written and verbal communication skills.",
    ],
    deadline: "30 Oct 2025",
  },
  {
    id: "intern-3",
    type: "internship",
    company: "Tata Consultancy Services",
    title: "TCS Prime Internship",
    badge: "Open",
    workMode: "Pan India (Hybrid)",
    location: "Pan India",
    duration: "Nov 2025 – Jan 2026 (3 months)",
    durationCategory: "1–3 months",
    skills: ["Java", "Python", "Data Analytics"],
    applications: "1.9k applied",
    applicationsCount: 1900,
    stipend: "₹35,000 / month",
    eligibility: "Open to pre-final & final year engineering students",
    openToAll: true,
    featured: true,
    saved: false,
    applied: false,
    logoType: "tcs",
    description:
      "TCS Prime offers student developers real-time industry projects across enterprise data engineering, financial automation pipelines, and hybrid cloud solutions.",
    requirements: [
      "Proficiency in Java or Python with standard database querying knowledge (SQL / NoSQL).",
      "Good academic track record across computer science fundamentals.",
      "Availability for 3 months hybrid internship across TCS innovation hubs.",
    ],
    deadline: "25 Oct 2025",
  },
  {
    id: "intern-4",
    type: "internship",
    company: "Zomato",
    title: "Zomato Engineering Internship",
    badge: "Limited Seats",
    workMode: "Remote",
    location: "Remote",
    duration: "Dec 2025 – Mar 2026 (4 months)",
    durationCategory: "3–6 months",
    skills: ["Frontend", "Backend", "React"],
    applications: "1.2k applied",
    applicationsCount: 1200,
    stipend: "₹50,000 / month",
    eligibility: "All branches with strong problem-solving and React skills",
    openToAll: true,
    featured: true,
    saved: false,
    applied: false,
    logoType: "zomato",
    description:
      "Join the fast-paced core engineering team behind Zomato food delivery and quick-commerce. Work on high-performance React frontends, real-time rider dispatch, and microservice APIs.",
    requirements: [
      "Strong proficiency in modern JavaScript/TypeScript, React.js, and RESTful APIs.",
      "Understanding of web performance optimization, state management, and clean architecture.",
      "Prior project showcase or active GitHub contributions.",
    ],
    deadline: "10 Nov 2025",
  },
  // Page 2 Internships
  {
    id: "intern-5",
    type: "internship",
    company: "Amazon",
    title: "Amazon SDE Summer Intern",
    badge: "High Demand",
    workMode: "Hybrid",
    location: "Bangalore",
    duration: "May 2026 – Jul 2026 (3 months)",
    durationCategory: "1–3 months",
    skills: ["Java", "AWS", "DSA"],
    applications: "4.5k applied",
    applicationsCount: 4500,
    stipend: "₹1,10,000 / month",
    eligibility: "Pre-final year B.Tech / M.Tech students",
    openToAll: false,
    featured: false,
    saved: false,
    applied: false,
    logoType: "amazon",
    description:
      "Software Development Engineer intern working on distributed systems, DynamoDB query optimizations, and automated checkout services for Amazon Retail.",
    requirements: ["Deep knowledge of algorithms, data structures, and object-oriented design in Java or C++."],
    deadline: "20 Nov 2025",
  },
  {
    id: "intern-6",
    type: "internship",
    company: "Adobe",
    title: "Adobe Research & ML Intern",
    badge: "Featured",
    workMode: "On-site",
    location: "Noida",
    duration: "Jan 2026 – Jun 2026 (6 months)",
    durationCategory: "6+ months",
    skills: ["Python", "Machine Learning", "Generative AI"],
    applications: "2.1k applied",
    applicationsCount: 2100,
    stipend: "₹90,000 / month",
    eligibility: "Open to CS/AI students with ML publication or projects",
    openToAll: false,
    featured: false,
    saved: false,
    applied: false,
    logoType: "adobe",
    description:
      "Explore generative image processing, diffusion model training, and Creative Cloud visual AI features at Adobe Media Intelligence Lab.",
    requirements: ["Experience with PyTorch, computer vision, and neural network fine-tuning."],
    deadline: "05 Dec 2025",
  },
  {
    id: "intern-7",
    type: "internship",
    company: "Uber",
    title: "Uber Backend Engineer Intern",
    badge: "Open",
    workMode: "Remote",
    location: "Remote / Hyderabad",
    duration: "Feb 2026 – May 2026 (4 months)",
    durationCategory: "3–6 months",
    skills: ["Go", "Node.js", "Kafka"],
    applications: "2.8k applied",
    applicationsCount: 2800,
    stipend: "₹95,000 / month",
    eligibility: "Open to 3rd & 4th year students",
    openToAll: true,
    featured: false,
    saved: false,
    applied: false,
    logoType: "uber",
    description:
      "Scale high-throughput streaming pipelines, driver location tracking, and real-time pricing algorithms using Go and Kafka.",
    requirements: ["Proficiency in backend development, concurrency, and distributed system basics."],
    deadline: "18 Nov 2025",
  },
  {
    id: "intern-8",
    type: "internship",
    company: "Flipkart",
    title: "Flipkart UI/UX Engineering Intern",
    badge: "Limited Seats",
    workMode: "Hybrid",
    location: "Bangalore",
    duration: "Jan 2026 – Apr 2026 (4 months)",
    durationCategory: "3–6 months",
    skills: ["React", "TypeScript", "Tailwind"],
    applications: "1.6k applied",
    applicationsCount: 1600,
    stipend: "₹55,000 / month",
    eligibility: "All engineering & design students",
    openToAll: true,
    featured: false,
    saved: false,
    applied: false,
    logoType: "flipkart",
    description:
      "Create accessible, blazing-fast mobile-web experiences for Flipkart's festival sale landing pages and interactive gamified commerce.",
    requirements: ["Portfolio of web applications, mastery of React, CSS animations, and responsive UI design."],
    deadline: "12 Dec 2025",
  },
];

// =============================================================================
// Core Hackathons Dataset (Page 1: items 1-4, Page 2: items 5-8)
// =============================================================================
export const INITIAL_HACKATHONS = [
  {
    id: "hack-1",
    type: "hackathon",
    company: "Google Developers",
    title: "Google GenAI Hackathon",
    badge: "Prize Pool",
    workMode: "Remote",
    mode: "Online",
    location: "Online / Global",
    duration: "10 Oct – 12 Oct 2025 (48 hours)",
    durationCategory: "1–3 months",
    skills: ["AI/ML", "Generative AI", "Web"],
    applications: "5.2k registered",
    registrationsCount: 5200,
    prize: "₹5,00,000 Prize Pool",
    eligibility: "Open to all enrolled university students worldwide",
    openToAll: true,
    featured: true,
    saved: false,
    applied: false,
    registered: false,
    logoType: "google-dev",
    description:
      "Build ground-breaking generative AI applications and agentic workflows using Google Gemini models, LangChain, and Firebase cloud services in this 48-hour global challenge.",
    requirements: [
      "Teams of 1 to 4 members.",
      "Projects must leverage Gemini API or Gemma open weights.",
      "Functional GitHub repository with video demonstration required upon submission.",
    ],
    deadline: "08 Oct 2025",
  },
  {
    id: "hack-2",
    type: "hackathon",
    company: "Microsoft",
    title: "Microsoft Imagine Cup",
    badge: "Popular",
    workMode: "Hybrid",
    mode: "Online / Hybrid",
    location: "Online / Hybrid",
    duration: "15 Nov – 17 Nov 2025 (72 hours)",
    durationCategory: "1–3 months",
    skills: ["Social Impact", "AI", "Sustainability"],
    applications: "8.7k registered",
    registrationsCount: 8700,
    prize: "$100,000 Global Grand Prize & Mentorship",
    eligibility: "Open to all undergraduate & postgraduate students",
    openToAll: true,
    featured: true,
    saved: true,
    applied: false,
    registered: false,
    logoType: "microsoft",
    description:
      "The premier global student technology competition empowering student founders to build solutions tackling health, environment, education, and social equity with Microsoft Azure.",
    requirements: [
      "Teams of up to 4 members.",
      "Working prototype hosted on Microsoft Azure cloud infrastructure.",
      "Executive pitch deck and technical demonstration.",
    ],
    deadline: "10 Nov 2025",
  },
  {
    id: "hack-3",
    type: "hackathon",
    company: "Devfolio",
    title: "Devfolio Buildathon",
    badge: "Open",
    workMode: "Remote",
    mode: "Online",
    location: "Online",
    duration: "1 Dec – 3 Dec 2025 (48 hours)",
    durationCategory: "1–3 months",
    skills: ["Web3", "Blockchain", "Web Dev"],
    applications: "4.3k registered",
    registrationsCount: 4300,
    prize: "₹3,50,000 + Grant Tracks",
    eligibility: "Open to all developers, designers, and web3 enthusiasts",
    openToAll: true,
    featured: true,
    saved: false,
    applied: false,
    registered: false,
    logoType: "devfolio",
    description:
      "A fast-paced developer sprint focused on next-generation decentralized apps, account abstraction, privacy-preserving zero-knowledge proofs, and decentralized identity.",
    requirements: [
      "Open source codebase published on GitHub with an open-source license.",
      "Smart contracts deployed on testnet/mainnet with verified contracts.",
      "Interactive frontend with web3 wallet connection.",
    ],
    deadline: "28 Nov 2025",
  },
  {
    id: "hack-4",
    type: "hackathon",
    company: "HackerEarth",
    title: "HackerEarth Coding Challenge",
    badge: "Trending",
    workMode: "Remote",
    mode: "Online",
    location: "Online",
    duration: "20 Oct – 22 Oct 2025 (48 hours)",
    durationCategory: "1–3 months",
    skills: ["DSA", "Algorithms", "Problem Solving"],
    applications: "12.6k registered",
    registrationsCount: 12600,
    prize: "₹2,00,000 + Direct Interview Shortlists",
    eligibility: "Open to all engineering students across all semesters",
    openToAll: true,
    featured: true,
    saved: false,
    applied: false,
    registered: false,
    logoType: "hackerearth",
    description:
      "A national competitive algorithmic coding marathon featuring real-world system optimization, dynamic programming challenges, and direct interview opportunities with hiring partners.",
    requirements: [
      "Individual participation.",
      "Automated evaluation across 5 algorithmic problem sets.",
      "Plagiarism monitoring and strict code originality checks.",
    ],
    deadline: "19 Oct 2025",
  },
  // Page 2 Hackathons
  {
    id: "hack-5",
    type: "hackathon",
    company: "Smart India",
    title: "Smart India Hackathon (SIH 2025)",
    badge: "Trending",
    workMode: "On-site",
    mode: "Grand Finale On-site",
    location: "New Delhi",
    duration: "10 Dec – 12 Dec 2025 (36 hours)",
    durationCategory: "1–3 months",
    skills: ["IoT", "AI/ML", "Hardware"],
    applications: "25k registered",
    registrationsCount: 25000,
    prize: "₹1,00,000 per problem statement",
    eligibility: "College-endorsed student teams",
    openToAll: false,
    featured: false,
    saved: false,
    applied: false,
    registered: false,
    logoType: "sih",
    description:
      "World's biggest open innovation model solving problem statements posed by central government ministries, departments, and industry leaders.",
    requirements: ["Teams of 6 members with mandatory 1 female member."],
    deadline: "15 Nov 2025",
  },
  {
    id: "hack-6",
    type: "hackathon",
    company: "ETHGlobal",
    title: "ETHIndia Hackathon 2025",
    badge: "Popular",
    workMode: "On-site",
    mode: "In-Person Bangalore",
    location: "Bangalore",
    duration: "05 Dec – 07 Dec 2025 (36 hours)",
    durationCategory: "1–3 months",
    skills: ["Solidity", "Ethereum", "DeFi"],
    applications: "6.8k registered",
    registrationsCount: 6800,
    prize: "$120,000 Track Bounties",
    eligibility: "Open to accepted applicants with hackathon pass",
    openToAll: true,
    featured: false,
    saved: false,
    applied: false,
    registered: false,
    logoType: "ethindia",
    description:
      "Asia's biggest Ethereum hackathon bringing together the world's best blockchain developers, founders, and protocols in Bangalore.",
    requirements: ["In-person hackathon attendance at KTPO Bangalore."],
    deadline: "10 Nov 2025",
  },
  {
    id: "hack-7",
    type: "hackathon",
    company: "AWS",
    title: "AWS Cloud Catalyst Hackathon",
    badge: "Prize Pool",
    workMode: "Remote",
    mode: "Online",
    location: "Online",
    duration: "18 Nov – 20 Nov 2025 (48 hours)",
    durationCategory: "1–3 months",
    skills: ["AWS", "Serverless", "Python"],
    applications: "4.1k registered",
    registrationsCount: 4100,
    prize: "$10,000 AWS Credits + Cash Rewards",
    eligibility: "Open to all college students",
    openToAll: true,
    featured: false,
    saved: false,
    applied: false,
    registered: false,
    logoType: "aws",
    description:
      "Build serverless microservices and agentic pipelines using AWS Bedrock, Lambda, DynamoDB, and CDK.",
    requirements: ["Functional AWS deployment with architectural diagram."],
    deadline: "14 Nov 2025",
  },
  {
    id: "hack-8",
    type: "hackathon",
    company: "Flipkart",
    title: "Flipkart GRiD 6.0 Challenge",
    badge: "Open",
    workMode: "Remote",
    mode: "Online / Virtual",
    location: "Online",
    duration: "25 Nov – 27 Nov 2025 (48 hours)",
    durationCategory: "1–3 months",
    skills: ["Robotics", "E-Commerce", "ML"],
    applications: "18k registered",
    registrationsCount: 18000,
    prize: "₹5,25,000 + PPI Offers",
    eligibility: "Open to B.Tech, B.E., M.Tech students",
    openToAll: false,
    featured: false,
    saved: false,
    applied: false,
    registered: false,
    logoType: "flipkart",
    description:
      "Flipkart's flagship campus technical competition spanning Software Development, Robotics, and Information Security problem tracks.",
    requirements: ["Teams of 2 to 3 students from the same college campus."],
    deadline: "20 Nov 2025",
  },
];

// =============================================================================
// Featured Opportunities (Sidebar)
// =============================================================================
export const FEATURED_OPPORTUNITIES = [
  {
    id: "intern-1",
    title: "Google STEP Internship",
    company: "Google",
    meta: "Google • Remote • 3 months",
    badge: "Featured",
    badgeColor: "emerald",
    logoType: "google",
  },
  {
    id: "intern-2",
    title: "Microsoft Explore Internship",
    company: "Microsoft",
    meta: "Microsoft • Hybrid • 4 months",
    badge: "High Demand",
    badgeColor: "amber",
    logoType: "microsoft",
  },
  {
    id: "intern-3",
    title: "TCS Prime Internship",
    company: "Tata Consultancy Services",
    meta: "Tata Consultancy Services • Pan India",
    badge: "Open",
    badgeColor: "sky",
    logoType: "tcs",
  },
  {
    id: "intern-4",
    title: "Zomato Engineering Internship",
    company: "Zomato",
    meta: "Zomato • Remote • 4 months",
    badge: "Limited Seats",
    badgeColor: "purple",
    logoType: "zomato",
  },
];
