/**
 * College OS Events Data
 * Structured dataset supporting filtering by Tab, Category, Search, Date & Pagination.
 */

export const CATEGORIES_LIST = [
  "All Categories",
  "Hackathon",
  "Workshop",
  "Cultural",
  "Sports",
  "Tech Talk",
  "Seminar",
  "Competition",
];

export const SIDEBAR_CATEGORIES = [
  "All",
  "Hackathon",
  "Workshop",
  "Cultural",
  "Sports",
  "Tech Talk",
  "Seminar",
];

export const ATTENDEE_AVATARS = [
  "/assets/events/avatars/avatar-1.jpg",
  "/assets/events/avatars/avatar-2.jpg",
  "/assets/events/avatars/avatar-3.jpg",
];

export const ALL_EVENTS = [
  {
    id: "event-1",
    title: "College Hackathon 2025",
    category: "Hackathon",
    badges: ["Featured", "🔥 Popular"],
    isFeatured: true,
    isPopular: true,
    description:
      "Build innovative solutions, collaborate with peers and win exciting prizes. Open for all branches!",
    date: "22 – 24 Aug 2025",
    fullDate: "August 22 – 24, 2025",
    time: "9:00 AM – 6:00 PM",
    venue: "Main Auditorium",
    participation: "Team (2–4 members)",
    goingCount: 248,
    status: "upcoming",
    image: "/assets/events/hackathon.jpg",
    actionType: "register",
    organizer: "Dept. of Computer Science & Innovation Cell",
    dayNumber: 22,
    hasImageOverlayBadge: "Featured",
    categoryTheme: {
      bg: "bg-purple-100 dark:bg-purple-950/60",
      text: "text-purple-700 dark:text-purple-300",
      border: "border-purple-200 dark:border-purple-800/50",
    },
  },
  {
    id: "event-2",
    title: "Next.js Workshop",
    category: "Workshop",
    badges: [],
    isFeatured: false,
    isPopular: false,
    description:
      "Learn Next.js 15 with real-world projects and build your own full-stack application.",
    date: "26 Aug 2025",
    time: "10:00 AM – 1:00 PM",
    venue: "Computer Lab 2",
    participation: "Individual",
    goingCount: 120,
    status: "upcoming",
    image: "/assets/events/nextjs-workshop.jpg",
    actionType: "register",
    organizer: "Web Development Club",
    dayNumber: 26,
    hasImageOverlayBadge: null,
    categoryTheme: {
      bg: "bg-sky-100 dark:bg-sky-950/60",
      text: "text-sky-700 dark:text-sky-300",
      border: "border-sky-200 dark:border-sky-800/50",
    },
  },
  {
    id: "event-3",
    title: "Freshers' Welcome 2025",
    category: "Cultural",
    badges: [],
    isFeatured: false,
    isPopular: false,
    description:
      "Join us for an exciting evening of music, dance, fun and fresh beginnings!",
    date: "30 Aug 2025",
    time: "5:00 PM – 9:00 PM",
    venue: "College Ground",
    participation: "All Students",
    goingCount: 306,
    status: "upcoming",
    image: "/assets/events/freshers-welcome.jpg",
    actionType: "interested",
    organizer: "Student Council & Cultural Society",
    dayNumber: 30,
    hasImageOverlayBadge: null,
    categoryTheme: {
      bg: "bg-rose-100 dark:bg-rose-950/60",
      text: "text-rose-700 dark:text-rose-300",
      border: "border-rose-200 dark:border-rose-800/50",
    },
  },
  {
    id: "event-4",
    title: "Tech Talk - Building Real World Startups",
    category: "Tech Talk",
    badges: [],
    isFeatured: false,
    isPopular: false,
    description:
      "Mr. Rohan Mehta (Founder, DevSummit) shares his journey from idea to product.",
    date: "22 Aug 2025",
    time: "10:00 AM – 12:00 PM",
    venue: "Seminar Hall",
    participation: "All Students",
    goingCount: 96,
    status: "upcoming",
    image: "/assets/events/tech-talk.jpg",
    actionType: "register",
    organizer: "E-Cell & Entrepreneurship Club",
    dayNumber: 22,
    hasImageOverlayBadge: null,
    categoryTheme: {
      bg: "bg-emerald-100 dark:bg-emerald-950/60",
      text: "text-emerald-700 dark:text-emerald-300",
      border: "border-emerald-200 dark:border-emerald-800/50",
    },
  },
  {
    id: "event-5",
    title: "Inter-College Football Tournament",
    category: "Sports",
    badges: [],
    isFeatured: false,
    isPopular: false,
    description:
      "Show your skills, represent your college and win the trophy!",
    date: "5 Sep 2025",
    time: "8:00 AM – 5:00 PM",
    venue: "Sports Ground",
    participation: "Team (11 players)",
    goingCount: 180,
    status: "upcoming",
    image: "/assets/events/football.jpg",
    actionType: "register",
    organizer: "College Sports Association",
    dayNumber: 5,
    hasImageOverlayBadge: null,
    categoryTheme: {
      bg: "bg-amber-100 dark:bg-amber-950/60",
      text: "text-amber-700 dark:text-amber-300",
      border: "border-amber-200 dark:border-amber-800/50",
    },
  },
  {
    id: "event-6",
    title: "UI/UX Design Workshop",
    category: "Workshop",
    badges: [],
    isFeatured: false,
    isPopular: false,
    description:
      "Learn the basics of UI/UX design, create wireframes and design your own app.",
    date: "10 Sep 2025",
    time: "2:00 PM – 5:00 PM",
    venue: "Design Lab",
    participation: "Individual",
    goingCount: 75,
    status: "upcoming",
    image: "/assets/events/uiux-workshop.jpg",
    actionType: "register",
    organizer: "Design & Media Society",
    dayNumber: 10,
    hasImageOverlayBadge: null,
    categoryTheme: {
      bg: "bg-sky-100 dark:bg-sky-950/60",
      text: "text-sky-700 dark:text-sky-300",
      border: "border-sky-200 dark:border-sky-800/50",
    },
  },
  {
    id: "event-7",
    title: "Autonomous Robotics Challenge",
    category: "Competition",
    badges: ["Featured"],
    isFeatured: true,
    isPopular: false,
    description:
      "Design, program, and race autonomous rovers through an intricate multi-terrain obstacle course.",
    date: "18 Aug 2025",
    time: "9:00 AM – 4:00 PM",
    venue: "Robotics Arena",
    participation: "Team (3–4 members)",
    goingCount: 142,
    status: "ongoing",
    image: "/assets/events/robotics.jpg",
    actionType: "register",
    organizer: "Robotics & Automation Club",
    dayNumber: 18,
    hasImageOverlayBadge: "Live",
    categoryTheme: {
      bg: "bg-indigo-100 dark:bg-indigo-950/60",
      text: "text-indigo-700 dark:text-indigo-300",
      border: "border-indigo-200 dark:border-indigo-800/50",
    },
  },
  {
    id: "event-8",
    title: "Modern AI & Data Science Symposium",
    category: "Seminar",
    badges: ["🔥 Popular"],
    isFeatured: false,
    isPopular: true,
    description:
      "Explore the cutting-edge advances in generative AI, neural networks, and campus research frontiers.",
    date: "18 Aug 2025",
    time: "11:00 AM – 3:00 PM",
    venue: "Amphitheater Hall",
    participation: "All Students",
    goingCount: 215,
    status: "ongoing",
    image: "/assets/events/ai-symposium.jpg",
    actionType: "register",
    organizer: "AI Research Group & IEEE Student Branch",
    dayNumber: 18,
    hasImageOverlayBadge: "Live",
    categoryTheme: {
      bg: "bg-teal-100 dark:bg-teal-950/60",
      text: "text-teal-700 dark:text-teal-300",
      border: "border-teal-200 dark:border-teal-800/50",
    },
  },
  {
    id: "event-9",
    title: "Inter-Department Badminton Championship",
    category: "Sports",
    badges: [],
    isFeatured: false,
    isPopular: false,
    description:
      "Singles and doubles knockout tournament between engineering departments with medal ceremonies.",
    date: "29 Aug 2025",
    time: "4:00 PM – 8:00 PM",
    venue: "Indoor Sports Complex",
    participation: "Individual / Doubles",
    goingCount: 64,
    status: "upcoming",
    image: "/assets/events/football.jpg",
    actionType: "register",
    organizer: "Sports Board",
    dayNumber: 29,
    hasImageOverlayBadge: null,
    categoryTheme: {
      bg: "bg-amber-100 dark:bg-amber-950/60",
      text: "text-amber-700 dark:text-amber-300",
      border: "border-amber-200 dark:border-amber-800/50",
    },
  },
  {
    id: "event-10",
    title: "Cloud Architecture & DevOps Bootcamp",
    category: "Workshop",
    badges: [],
    isFeatured: false,
    isPopular: false,
    description:
      "Hands-on cloud deployment, container orchestration with Docker and CI/CD pipelines on AWS.",
    date: "14 Sep 2025",
    time: "10:00 AM – 2:00 PM",
    venue: "Computer Lab 1",
    participation: "Individual",
    goingCount: 88,
    status: "upcoming",
    image: "/assets/events/nextjs-workshop.jpg",
    actionType: "register",
    organizer: "Cloud Computing Club",
    dayNumber: 14,
    hasImageOverlayBadge: null,
    categoryTheme: {
      bg: "bg-sky-100 dark:bg-sky-950/60",
      text: "text-sky-700 dark:text-sky-300",
      border: "border-sky-200 dark:border-sky-800/50",
    },
  },
  {
    id: "event-11",
    title: "Alumni Leadership Panel & Networking",
    category: "Seminar",
    badges: [],
    isFeatured: false,
    isPopular: false,
    description:
      "Distinguished alumni from top tech and consulting firms discuss career pathways and mentoring.",
    date: "10 Aug 2025",
    time: "3:00 PM – 6:00 PM",
    venue: "Auditorium 2",
    participation: "All Students",
    goingCount: 190,
    status: "past",
    image: "/assets/events/tech-talk.jpg",
    actionType: "interested",
    organizer: "Alumni Relations Office",
    dayNumber: 10,
    hasImageOverlayBadge: "Completed",
    categoryTheme: {
      bg: "bg-slate-100 dark:bg-slate-800",
      text: "text-slate-700 dark:text-slate-300",
      border: "border-slate-200 dark:border-slate-700",
    },
  },
  {
    id: "event-12",
    title: "Annual Open Source HackFest 2025",
    category: "Hackathon",
    badges: [],
    isFeatured: false,
    isPopular: false,
    description:
      "48-hour sprint contributing to major open-source repositories with mentor reviews and swag.",
    date: "5 Aug 2025",
    time: "10:00 AM – 6:00 PM",
    venue: "Innovation Center",
    participation: "Team (2–3 members)",
    goingCount: 220,
    status: "past",
    image: "/assets/events/hackathon.jpg",
    actionType: "register",
    organizer: "Open Source Collective",
    dayNumber: 5,
    hasImageOverlayBadge: "Completed",
    categoryTheme: {
      bg: "bg-slate-100 dark:bg-slate-800",
      text: "text-slate-700 dark:text-slate-300",
      border: "border-slate-200 dark:border-slate-700",
    },
  },
];

// Highlighted event days for August 2025 calendar
export const AUGUST_2025_EVENT_DAYS = [18, 22, 26, 29];

// Quick upcoming list for the right sidebar
export const SIDEBAR_UPCOMING_EVENTS = [
  {
    id: "event-2",
    title: "Next.js Workshop",
    timeString: "26 Aug 2025 • 10:00 AM",
    category: "Workshop",
    iconType: "laptop",
    iconBg: "bg-sky-100 dark:bg-sky-900/40",
    iconColor: "text-sky-600 dark:text-sky-400",
  },
  {
    id: "event-4",
    title: "Tech Talk - Building Real World Startups",
    timeString: "22 Aug 2025 • 10:00 AM",
    category: "Tech Talk",
    iconType: "mic",
    iconBg: "bg-emerald-100 dark:bg-emerald-900/40",
    iconColor: "text-emerald-600 dark:text-emerald-400",
  },
  {
    id: "event-5",
    title: "Inter-College Football Tournament",
    timeString: "5 Sep 2025 • 8:00 AM",
    category: "Sports",
    iconType: "trophy",
    iconBg: "bg-amber-100 dark:bg-amber-900/40",
    iconColor: "text-amber-600 dark:text-amber-400",
  },
  {
    id: "event-6",
    title: "UI/UX Design Workshop",
    timeString: "10 Sep 2025 • 2:00 PM",
    category: "Workshop",
    iconType: "palette",
    iconBg: "bg-purple-100 dark:bg-purple-900/40",
    iconColor: "text-purple-600 dark:text-purple-400",
  },
];
