export const PROFILE_DATA = {
  user: {
    name: "Hamid Rza",
    isVerified: true,
    degree: "B.Tech",
    semester: "7th Semester",
    branch: "CSE",
    college: "XYZ College of Engineering, Mumbai",
    quote: "Small steps every day lead to big results.",
    avatar: "/assets/profile/avatar.jpg",
    stats: {
      projects: 12,
      followers: 3,
      following: 5,
    },
  },
  tabs: ["Overview", "About", "Skills", "Projects", "Achievements", "Activity"],
  about: {
    bio: "I'm a B.Tech CSE student with a strong interest in full-stack development, building real-world products and learning new technologies. I enjoy working on meaningful projects, exploring AI, and connecting with like-minded people. Always trying to improve, stay consistent and create something valuable.",
    email: "hamidrza0008@gmail.com",
    phone: "+91 98765 43210",
    location: "Mumbai, Maharashtra",
    quoteCard: {
      lines: ["Better", "Code", "Better", "Solutions"],
    },
  },
  quickInfo: [
    { label: "Roll No.", value: "CSE-302", icon: "hash" },
    { label: "Batch", value: "2022 - 2026", icon: "calendar" },
    { label: "Department", value: "Computer Science & Engineering", icon: "network" },
    { label: "Current Semester", value: "7th Semester", icon: "layers" },
    { label: "College", value: "XYZ College of Engineering", icon: "building" },
    { label: "Blood Group", value: "B+", icon: "droplet" },
    { label: "Gender", value: "Male", icon: "user" },
    { label: "Date of Birth", value: "12 Jan 2003", icon: "cake" },
  ],
  stats: {
    attendance: {
      percentage: 78,
      details: "16 / 21 classes attended",
    },
    cgpa: {
      value: "8.24",
      details: "Current Sem 7",
    },
    credits: {
      value: "142 / 160",
      details: "Completed",
    },
  },
  upcomingAssignments: {
    count: 3,
    period: "Due this week",
    partnerInfo: "Top Partners",
  },
  recentActivity: [
    {
      id: 1,
      title: "Submitted Assignment: Web Development",
      time: "2 hours ago",
      badge: "Submitted",
      type: "submitted",
    },
    {
      id: 2,
      title: "Joined Event: Tech Talk - AI in Modern World",
      time: "5 hours ago",
      badge: "Event",
      type: "event",
    },
    {
      id: 3,
      title: "Updated Project: College OS",
      time: "1 day ago",
      badge: "Project",
      type: "project",
    },
    {
      id: 4,
      title: "New Notice: College Fest Registration is live",
      time: "2 days ago",
      badge: "Notice",
      type: "notice",
    },
    {
      id: 5,
      title: "Completed: Data Structures & Algorithms (Level 1)",
      time: "3 days ago",
      badge: "Learning",
      type: "learning",
    },
  ],
  achievements: [
    {
      id: "learner",
      title: "Consistent Learner",
      subtitle: "Keep it up!",
      badge: "/assets/profile/badge-consistent-learner.svg",
    },
    {
      id: "builder",
      title: "Project Builder",
      subtitle: "3+ Projects",
      badge: "/assets/profile/badge-project-builder.svg",
    },
    {
      id: "attendee",
      title: "Event Attendee",
      subtitle: "5+ Events",
      badge: "/assets/profile/badge-event-attendee.svg",
    },
  ],
  skills: [
    "Next.js",
    "React.js",
    "Node.js",
    "Express.js",
    "MongoDB",
    "MySQL",
    "JavaScript",
    "Tailwind CSS",
    "Redux Toolkit",
    "Framer Motion",
    "Git",
    "Postman",
  ],
  completion: {
    percentage: 85,
    title: "Almost there!",
    description: "Complete your profile to unlock more features.",
    checklist: [
      { label: "Basic Information", completed: true },
      { label: "Education Details", completed: true },
      { label: "Skills & Interests", completed: true },
      { label: "Social Links", completed: true },
      { label: "Add Profile Banner", completed: false },
    ],
  },
  socialLinks: [
    {
      platform: "Github",
      handle: "github.com/hamidrza0008",
      url: "https://github.com/hamidrza0008",
      type: "github",
    },
    {
      platform: "Linkedin",
      handle: "linkedin.com/in/hamidrza",
      url: "https://linkedin.com/in/hamidrza",
      type: "linkedin",
    },
    {
      platform: "Portfolio",
      handle: "hamid.dev",
      url: "https://hamid.dev",
      type: "portfolio",
    },
  ],
  interests: [
    "Web Development",
    "AI & ML",
    "Open Source",
    "Travel",
    "Fitness",
    "Reading",
  ],
  campusAiPromo: {
    title: "Get More from\nCampus AI",
    description: "Your personal AI assistant for college queries, notes, and more.",
    buttonText: "Try Campus AI →",
  },
};
