// ─────────────────────────────────────────────────────────────────────────────
// subjectDetailsData.js
// Rich data model for /student/academics/subjects/[code]
// ─────────────────────────────────────────────────────────────────────────────

export const SUBJECT_DETAILS_MAP = {
  "CSE-302-dsa": {
    id: "sub-1",
    code: "CSE-302",
    slug: "CSE-302-dsa",
    name: "Data Structures & Algorithms",
    fullName: "Data Structures & Algorithms",
    credits: 4,
    semester: 7,
    type: "Theory",
    icon: "code",
    color: "emerald",
    department: "Computer Science & Engineering",
    lectureRoom: "CS Block — Room 301",
    lectureTimings: "Mon, Wed, Fri — 9:00 AM to 10:00 AM",
    totalLectures: 60,
    conductedLectures: 55,
    currentGrade: "A",
    progress: 92,
    faculty: {
      name: "Dr. Priya Sharma",
      designation: "Associate Professor",
      department: "CSE Department",
      email: "priya.sharma@college.edu",
      phone: "+91 98765 43210",
      officeRoom: "Faculty Block — Room F-12",
      officeHours: [
        { day: "Monday", time: "11:00 AM – 12:30 PM" },
        { day: "Wednesday", time: "2:00 PM – 3:30 PM" },
        { day: "Friday", time: "11:00 AM – 12:00 PM" },
      ],
      avatar: null,
    },
    attendance: {
      percentage: 92,
      conducted: 55,
      attended: 51,
      absent: 4,
      minRequired: 75,
      monthlyBreakdown: [
        { month: "Jun", conducted: 12, attended: 12 },
        { month: "Jul", conducted: 18, attended: 16 },
        { month: "Aug", conducted: 16, attended: 15 },
        { month: "Sep", conducted: 9, attended: 8 },
      ],
    },
    internalMarks: {
      maxMarks: 60,
      breakdown: [
        { component: "Internal Assessment 1 (IA-1)", max: 20, scored: 18, status: "completed" },
        { component: "Internal Assessment 2 (IA-2)", max: 20, scored: 17, status: "completed" },
        { component: "Assignment & Lab Work", max: 10, scored: 9, status: "completed" },
        { component: "Seminar / Viva", max: 10, scored: null, status: "upcoming" },
      ],
      totalScored: 44,
      totalMax: 60,
      grade: "A",
    },
    units: [
      { id: "u1", number: 1, title: "Introduction to Data Structures", topics: ["Arrays and Strings","Linked Lists (Singly, Doubly, Circular)","Stack and Queue ADT","Time and Space Complexity — Big-O Notation"], status: "completed", progress: 100 },
      { id: "u2", number: 2, title: "Trees and Hierarchical Structures", topics: ["Binary Trees and BST","AVL Trees (Rotations)","Heap and Priority Queue","B-Trees and B+ Trees"], status: "completed", progress: 100 },
      { id: "u3", number: 3, title: "Graph Theory and Traversal", topics: ["Graph Representations (Adjacency Matrix / List)","BFS and DFS Traversal","Shortest Path — Dijkstra, Bellman-Ford","Minimum Spanning Trees — Kruskal & Prim"], status: "completed", progress: 100 },
      { id: "u4", number: 4, title: "Sorting and Searching Algorithms", topics: ["Comparison Based Sorts (Merge, Quick, Heap Sort)","Non-Comparison Sorts (Counting, Radix)","Binary Search and Variants","Hashing — Hash Functions and Collision Resolution"], status: "in-progress", progress: 60 },
      { id: "u5", number: 5, title: "Dynamic Programming & Greedy Algorithms", topics: ["Memoization vs Tabulation","Classic DP Problems — Knapsack, LCS, LIS","Greedy Strategy and Activity Selection","Backtracking — N-Queens, Sudoku Solver"], status: "upcoming", progress: 0 },
    ],
    resources: [
      { id: "r1", title: "Unit 1 — Arrays & Linked Lists (Lecture Notes)", type: "PDF", size: "2.4 MB", uploadedOn: "12 Jun 2025", unit: "Unit 1", downloads: 142 },
      { id: "r2", title: "Unit 2 — Trees (Slides)", type: "PPT", size: "4.8 MB", uploadedOn: "28 Jun 2025", unit: "Unit 2", downloads: 138 },
      { id: "r3", title: "Unit 3 — Graph Theory (Reference)", type: "PDF", size: "3.1 MB", uploadedOn: "14 Jul 2025", unit: "Unit 3", downloads: 120 },
      { id: "r4", title: "Unit 4 — Sorting Algorithms (Slides)", type: "PPT", size: "5.2 MB", uploadedOn: "05 Aug 2025", unit: "Unit 4", downloads: 95 },
      { id: "r5", title: "DSA Complete Problem Set (Practice)", type: "PDF", size: "8.7 MB", uploadedOn: "01 Aug 2025", unit: "All Units", downloads: 212 },
    ],
    assignments: [
      { id: "asgn-1", title: "Implement AVL Tree with Rotations", dueDate: "25 Aug 2025", status: "submitted", marks: "18/20" },
      { id: "asgn-2", title: "Graph Shortest Path — Dijkstra Implementation", dueDate: "10 Sep 2025", status: "pending", marks: null },
      { id: "asgn-3", title: "Dynamic Programming — Knapsack Problem", dueDate: "28 Sep 2025", status: "upcoming", marks: null },
    ],
    exam: { date: "20 Aug 2025", time: "10:00 AM – 01:00 PM", venue: "Exam Hall B — Block C", type: "University End-Semester Exam", syllabus: "All 5 units — Open Book: No" },
  },

  "CSE-101": {
    id: "sub-2",
    code: "CSE-101",
    slug: "CSE-101",
    name: "Web Development",
    fullName: "Web Development",
    credits: 4,
    semester: 7,
    type: "Theory",
    icon: "globe",
    color: "blue",
    department: "Computer Science & Engineering",
    lectureRoom: "CS Block — Room 205",
    lectureTimings: "Tue, Thu — 10:00 AM to 11:30 AM",
    totalLectures: 52,
    conductedLectures: 48,
    currentGrade: "A-",
    progress: 86,
    faculty: {
      name: "Prof. Arjun Mehta",
      designation: "Assistant Professor",
      department: "CSE Department",
      email: "arjun.mehta@college.edu",
      phone: "+91 91234 56789",
      officeRoom: "Faculty Block — Room F-08",
      officeHours: [
        { day: "Tuesday", time: "12:00 PM – 1:30 PM" },
        { day: "Thursday", time: "3:00 PM – 4:30 PM" },
      ],
      avatar: null,
    },
    attendance: {
      percentage: 87,
      conducted: 48,
      attended: 42,
      absent: 6,
      minRequired: 75,
      monthlyBreakdown: [
        { month: "Jun", conducted: 10, attended: 9 },
        { month: "Jul", conducted: 16, attended: 14 },
        { month: "Aug", conducted: 14, attended: 13 },
        { month: "Sep", conducted: 8, attended: 6 },
      ],
    },
    internalMarks: {
      maxMarks: 60,
      breakdown: [
        { component: "Internal Assessment 1 (IA-1)", max: 20, scored: 16, status: "completed" },
        { component: "Internal Assessment 2 (IA-2)", max: 20, scored: 17, status: "completed" },
        { component: "Assignment & Lab Work", max: 10, scored: 8, status: "completed" },
        { component: "Seminar / Viva", max: 10, scored: null, status: "upcoming" },
      ],
      totalScored: 41,
      totalMax: 60,
      grade: "A-",
    },
    units: [
      { id: "u1", number: 1, title: "HTML5 & Semantic Markup", topics: ["Document Structure","Forms & Validation","Accessibility (ARIA)","SEO Best Practices"], status: "completed", progress: 100 },
      { id: "u2", number: 2, title: "CSS3 & Modern Layouts", topics: ["Flexbox & CSS Grid","Animations & Transitions","CSS Variables & Theming","Responsive Design"], status: "completed", progress: 100 },
      { id: "u3", number: 3, title: "JavaScript & DOM APIs", topics: ["ES6+ Features","Async/Await & Promises","DOM Manipulation","Fetch API & REST"], status: "completed", progress: 100 },
      { id: "u4", number: 4, title: "React.js Framework", topics: ["Components & Props","State Management (Hooks)","React Router","Context API & useReducer"], status: "in-progress", progress: 70 },
      { id: "u5", number: 5, title: "Node.js & Backend Basics", topics: ["Express.js REST APIs","JWT Authentication","MongoDB & Mongoose","Deployment (Vercel / Railway)"], status: "upcoming", progress: 0 },
    ],
    resources: [
      { id: "r1", title: "HTML5 Semantic & Forms (Notes)", type: "PDF", size: "1.8 MB", uploadedOn: "10 Jun 2025", unit: "Unit 1", downloads: 89 },
      { id: "r2", title: "CSS Grid & Flexbox Cheatsheet", type: "PDF", size: "0.9 MB", uploadedOn: "01 Jul 2025", unit: "Unit 2", downloads: 145 },
      { id: "r3", title: "React.js Slides & Lab Guide", type: "PPT", size: "6.2 MB", uploadedOn: "10 Aug 2025", unit: "Unit 4", downloads: 112 },
    ],
    assignments: [
      { id: "asgn-1", title: "Build a Responsive Portfolio Page", dueDate: "20 Jul 2025", status: "submitted", marks: "9/10" },
      { id: "asgn-2", title: "Create a React To-Do App with Hooks", dueDate: "15 Sep 2025", status: "pending", marks: null },
    ],
    exam: { date: "24 Aug 2025", time: "10:00 AM – 01:00 PM", venue: "Exam Hall A — Block B", type: "University End-Semester Exam", syllabus: "Units 1–5" },
  },

  "CSE-302-dbms": {
    id: "sub-3",
    code: "CSE-302",
    slug: "CSE-302-dbms",
    name: "Database Management Systems",
    fullName: "Database Management Systems",
    credits: 4,
    semester: 7,
    type: "Theory",
    icon: "database",
    color: "purple",
    department: "Computer Science & Engineering",
    lectureRoom: "CS Block — Room 308",
    lectureTimings: "Mon, Wed — 11:00 AM to 12:30 PM",
    totalLectures: 48,
    conductedLectures: 42,
    currentGrade: "B+",
    progress: 82,
    faculty: {
      name: "Dr. Neha Kapoor",
      designation: "Associate Professor",
      department: "CSE Department",
      email: "neha.kapoor@college.edu",
      phone: "+91 90000 12345",
      officeRoom: "Faculty Block — Room F-15",
      officeHours: [
        { day: "Monday", time: "1:00 PM – 2:30 PM" },
        { day: "Wednesday", time: "3:00 PM – 4:00 PM" },
      ],
      avatar: null,
    },
    attendance: {
      percentage: 83,
      conducted: 42,
      attended: 35,
      absent: 7,
      minRequired: 75,
      monthlyBreakdown: [
        { month: "Jun", conducted: 8, attended: 7 },
        { month: "Jul", conducted: 14, attended: 12 },
        { month: "Aug", conducted: 12, attended: 10 },
        { month: "Sep", conducted: 8, attended: 6 },
      ],
    },
    internalMarks: {
      maxMarks: 60,
      breakdown: [
        { component: "Internal Assessment 1 (IA-1)", max: 20, scored: 15, status: "completed" },
        { component: "Internal Assessment 2 (IA-2)", max: 20, scored: 16, status: "completed" },
        { component: "Assignment & Lab Work", max: 10, scored: 8, status: "completed" },
        { component: "Seminar / Viva", max: 10, scored: null, status: "upcoming" },
      ],
      totalScored: 39,
      totalMax: 60,
      grade: "B+",
    },
    units: [
      { id: "u1", number: 1, title: "Database Concepts & ER Model", topics: ["Relational Model","ER Diagrams","Keys and Constraints","Schema Design"], status: "completed", progress: 100 },
      { id: "u2", number: 2, title: "SQL — DDL & DML", topics: ["CREATE / ALTER / DROP","SELECT Queries","Joins and Subqueries","Aggregate Functions"], status: "completed", progress: 100 },
      { id: "u3", number: 3, title: "Normalization", topics: ["1NF, 2NF, 3NF","BCNF","Decomposition","Functional Dependencies"], status: "completed", progress: 100 },
      { id: "u4", number: 4, title: "Transactions & Concurrency", topics: ["ACID Properties","Isolation Levels","Deadlock Handling","Two-Phase Locking"], status: "in-progress", progress: 50 },
      { id: "u5", number: 5, title: "Indexing & Query Optimization", topics: ["B+ Tree Indexing","Query Processing Stages","Cost Estimation","NoSQL Intro"], status: "upcoming", progress: 0 },
    ],
    resources: [
      { id: "r1", title: "ER Model & SQL Basics (Notes)", type: "PDF", size: "2.1 MB", uploadedOn: "15 Jun 2025", unit: "Unit 1", downloads: 78 },
      { id: "r2", title: "Normalization Worksheet", type: "PDF", size: "1.2 MB", uploadedOn: "20 Jul 2025", unit: "Unit 3", downloads: 95 },
      { id: "r3", title: "Transactions & Concurrency (Slides)", type: "PPT", size: "3.8 MB", uploadedOn: "01 Aug 2025", unit: "Unit 4", downloads: 67 },
    ],
    assignments: [
      { id: "asgn-1", title: "Design ER Diagram for Library System", dueDate: "10 Jul 2025", status: "submitted", marks: "8/10" },
      { id: "asgn-2", title: "Normalize a Given Database Schema (3NF)", dueDate: "05 Sep 2025", status: "pending", marks: null },
    ],
    exam: { date: "28 Aug 2025", time: "10:00 AM – 01:00 PM", venue: "Exam Hall C — Block A", type: "University End-Semester Exam", syllabus: "Units 1–5" },
  },

  "Lab-2": {
    id: "sub-4",
    code: "Lab-2",
    slug: "Lab-2",
    name: "Computer Networks Lab",
    fullName: "Computer Networks Practical Lab",
    credits: 2,
    semester: 7,
    type: "Practical",
    icon: "flask",
    color: "teal",
    department: "Computer Science & Engineering",
    lectureRoom: "Networks Lab — Block D, Room L-02",
    lectureTimings: "Thursday — 1:00 PM to 4:00 PM",
    totalLectures: 30,
    conductedLectures: 28,
    currentGrade: "A",
    progress: 95,
    faculty: {
      name: "Mr. Suresh Nair",
      designation: "Lab Instructor",
      department: "CSE Department",
      email: "suresh.nair@college.edu",
      phone: "+91 87654 32109",
      officeRoom: "Lab Block — Room L-04",
      officeHours: [
        { day: "Thursday", time: "12:00 PM – 1:00 PM" },
        { day: "Friday", time: "10:00 AM – 11:00 AM" },
      ],
      avatar: null,
    },
    attendance: {
      percentage: 96,
      conducted: 28,
      attended: 27,
      absent: 1,
      minRequired: 80,
      monthlyBreakdown: [
        { month: "Jun", conducted: 6, attended: 6 },
        { month: "Jul", conducted: 9, attended: 9 },
        { month: "Aug", conducted: 9, attended: 8 },
        { month: "Sep", conducted: 4, attended: 4 },
      ],
    },
    internalMarks: {
      maxMarks: 50,
      breakdown: [
        { component: "Lab Record & Journal", max: 15, scored: 14, status: "completed" },
        { component: "Mid Lab Test", max: 20, scored: 18, status: "completed" },
        { component: "Viva Voce", max: 15, scored: null, status: "upcoming" },
      ],
      totalScored: 32,
      totalMax: 50,
      grade: "A",
    },
    units: [
      { id: "u1", number: 1, title: "Socket Programming & OSI Model", topics: ["TCP/IP Basics","Socket API (C/Python)","Client-Server Programs","Packet Capture with Wireshark"], status: "completed", progress: 100 },
      { id: "u2", number: 2, title: "Routing Protocols", topics: ["Static Routing","RIP & OSPF Configuration","Cisco Packet Tracer","Subnetting & VLSM"], status: "completed", progress: 100 },
      { id: "u3", number: 3, title: "Application Layer Protocols", topics: ["HTTP & HTTPS","FTP & SSH","DNS Configuration","SMTP & POP3"], status: "completed", progress: 100 },
      { id: "u4", number: 4, title: "Network Security Basics", topics: ["Firewalls & NAT","ARP Spoofing Demo","SSL/TLS Handshake","VPN Concepts"], status: "in-progress", progress: 75 },
      { id: "u5", number: 5, title: "Final Lab Project", topics: ["Mini LAN Setup","Traffic Analysis Report","Security Audit","Presentation"], status: "upcoming", progress: 0 },
    ],
    resources: [
      { id: "r1", title: "Lab Manual — Full (Experiments 1–12)", type: "PDF", size: "5.4 MB", uploadedOn: "01 Jun 2025", unit: "All Units", downloads: 165 },
      { id: "r2", title: "Packet Tracer Sample Configs", type: "ZIP", size: "2.1 MB", uploadedOn: "05 Jul 2025", unit: "Unit 2", downloads: 88 },
    ],
    assignments: [
      { id: "asgn-1", title: "Lab Record — Experiments 1 to 6", dueDate: "15 Aug 2025", status: "submitted", marks: "28/30" },
      { id: "asgn-2", title: "Mini LAN Setup Report", dueDate: "02 Oct 2025", status: "upcoming", marks: null },
    ],
    exam: { date: "02 Sep 2025", time: "09:00 AM – 12:00 PM", venue: "Networks Lab — Block D", type: "Practical Exam", syllabus: "Experiments 1–12" },
  },

  "Lab-1": {
    id: "sub-5",
    code: "Lab-1",
    slug: "Lab-1",
    name: "Web Development Lab",
    fullName: "Web Development Practical Lab",
    credits: 2,
    semester: 7,
    type: "Practical",
    icon: "laptop",
    color: "indigo",
    department: "Computer Science & Engineering",
    lectureRoom: "Web Dev Lab — CS Block, Room L-01",
    lectureTimings: "Friday — 1:00 PM to 4:00 PM",
    totalLectures: 28,
    conductedLectures: 26,
    currentGrade: "A-",
    progress: 90,
    faculty: {
      name: "Ms. Pooja Iyer",
      designation: "Lab Instructor",
      department: "CSE Department",
      email: "pooja.iyer@college.edu",
      phone: "+91 76543 21098",
      officeRoom: "Lab Block — Room L-01",
      officeHours: [
        { day: "Wednesday", time: "11:00 AM – 12:00 PM" },
        { day: "Friday", time: "12:00 PM – 1:00 PM" },
      ],
      avatar: null,
    },
    attendance: {
      percentage: 92,
      conducted: 26,
      attended: 24,
      absent: 2,
      minRequired: 80,
      monthlyBreakdown: [
        { month: "Jun", conducted: 5, attended: 5 },
        { month: "Jul", conducted: 8, attended: 8 },
        { month: "Aug", conducted: 8, attended: 7 },
        { month: "Sep", conducted: 5, attended: 4 },
      ],
    },
    internalMarks: {
      maxMarks: 50,
      breakdown: [
        { component: "Lab Record & Exercises", max: 15, scored: 13, status: "completed" },
        { component: "Mid Lab Test", max: 20, scored: 17, status: "completed" },
        { component: "Viva Voce", max: 15, scored: null, status: "upcoming" },
      ],
      totalScored: 30,
      totalMax: 50,
      grade: "A-",
    },
    units: [
      { id: "u1", number: 1, title: "HTML & CSS Fundamentals", topics: ["Forms & Tables","Flexbox Layout","Animations","Responsive Breakpoints"], status: "completed", progress: 100 },
      { id: "u2", number: 2, title: "JavaScript DOM Projects", topics: ["Event Listeners","LocalStorage","Fetch API Project","Validation Scripts"], status: "completed", progress: 100 },
      { id: "u3", number: 3, title: "React Mini Projects", topics: ["Counter App","Todo with Hooks","Weather API App","Portfolio Site"], status: "completed", progress: 100 },
      { id: "u4", number: 4, title: "Full-Stack Mini App", topics: ["Express.js REST API","MongoDB CRUD","JWT Auth","React + Node Integration"], status: "in-progress", progress: 50 },
    ],
    resources: [
      { id: "r1", title: "Web Dev Lab Manual", type: "PDF", size: "3.2 MB", uploadedOn: "02 Jun 2025", unit: "All Units", downloads: 130 },
      { id: "r2", title: "React Projects Starter Kit", type: "ZIP", size: "4.5 MB", uploadedOn: "20 Jul 2025", unit: "Unit 3", downloads: 97 },
    ],
    assignments: [
      { id: "asgn-1", title: "Build a Portfolio Page with CSS Grid", dueDate: "10 Jul 2025", status: "submitted", marks: "9/10" },
      { id: "asgn-2", title: "Full-Stack MERN Blog App", dueDate: "10 Oct 2025", status: "upcoming", marks: null },
    ],
    exam: { date: "15 Sep 2025", time: "01:00 PM – 04:00 PM", venue: "Web Dev Lab — CS Block", type: "Practical Exam", syllabus: "All practical exercises" },
  },

  "OEC-101": {
    id: "sub-6",
    code: "OEC-101",
    slug: "OEC-101",
    name: "Elective / Open Elective",
    fullName: "Open Elective — Artificial Intelligence Fundamentals",
    credits: 3,
    semester: 7,
    type: "Theory",
    icon: "star",
    color: "amber",
    department: "Interdisciplinary Studies",
    lectureRoom: "Main Block — Seminar Hall B",
    lectureTimings: "Tuesday, Saturday — 2:00 PM to 3:00 PM",
    totalLectures: 36,
    conductedLectures: 30,
    currentGrade: "B+",
    progress: 78,
    faculty: {
      name: "Dr. Rohan Desai",
      designation: "Professor",
      department: "AI & Data Science",
      email: "rohan.desai@college.edu",
      phone: "+91 99887 76655",
      officeRoom: "AI Block — Room A-05",
      officeHours: [
        { day: "Tuesday", time: "3:00 PM – 4:30 PM" },
        { day: "Saturday", time: "10:00 AM – 12:00 PM" },
      ],
      avatar: null,
    },
    attendance: {
      percentage: 80,
      conducted: 30,
      attended: 24,
      absent: 6,
      minRequired: 75,
      monthlyBreakdown: [
        { month: "Jun", conducted: 6, attended: 5 },
        { month: "Jul", conducted: 10, attended: 8 },
        { month: "Aug", conducted: 9, attended: 7 },
        { month: "Sep", conducted: 5, attended: 4 },
      ],
    },
    internalMarks: {
      maxMarks: 60,
      breakdown: [
        { component: "Internal Assessment 1 (IA-1)", max: 20, scored: 14, status: "completed" },
        { component: "Internal Assessment 2 (IA-2)", max: 20, scored: 15, status: "completed" },
        { component: "Assignment & Quiz", max: 10, scored: 8, status: "completed" },
        { component: "Seminar", max: 10, scored: null, status: "upcoming" },
      ],
      totalScored: 37,
      totalMax: 60,
      grade: "B+",
    },
    units: [
      { id: "u1", number: 1, title: "Introduction to AI & Search", topics: ["History of AI","Problem Solving","BFS / DFS for AI","A* Algorithm"], status: "completed", progress: 100 },
      { id: "u2", number: 2, title: "Knowledge Representation", topics: ["Propositional Logic","First-Order Logic","Ontologies","Rule-Based Systems"], status: "completed", progress: 100 },
      { id: "u3", number: 3, title: "Machine Learning Basics", topics: ["Supervised vs Unsupervised","Linear & Logistic Regression","Decision Trees","Evaluation Metrics"], status: "completed", progress: 100 },
      { id: "u4", number: 4, title: "Neural Networks", topics: ["Perceptron Model","Backpropagation","CNNs","Transfer Learning"], status: "in-progress", progress: 40 },
      { id: "u5", number: 5, title: "AI Ethics & Applications", topics: ["Bias in AI","Explainable AI","NLP Introduction","AI in Healthcare & Finance"], status: "upcoming", progress: 0 },
    ],
    resources: [
      { id: "r1", title: "AI Fundamentals — Lecture Slides (Unit 1-3)", type: "PPT", size: "7.1 MB", uploadedOn: "15 Jun 2025", unit: "Units 1–3", downloads: 68 },
      { id: "r2", title: "Machine Learning Cheatsheet", type: "PDF", size: "1.4 MB", uploadedOn: "10 Jul 2025", unit: "Unit 3", downloads: 89 },
    ],
    assignments: [
      { id: "asgn-1", title: "Implement A* Search Algorithm", dueDate: "25 Jul 2025", status: "submitted", marks: "8/10" },
      { id: "asgn-2", title: "Build a Simple Neural Network from Scratch", dueDate: "20 Sep 2025", status: "pending", marks: null },
    ],
    exam: { date: "20 Sep 2025", time: "2:00 PM – 05:00 PM", venue: "Main Block — Hall C", type: "University End-Semester Exam", syllabus: "Units 1–5" },
  },
};

export const SUBJECT_CODE_TO_SLUG = {
  "sub-1": "CSE-302-dsa",
  "sub-2": "CSE-101",
  "sub-3": "CSE-302-dbms",
  "sub-4": "Lab-2",
  "sub-5": "Lab-1",
  "sub-6": "OEC-101",
};

export function getSubjectDetails(slug) {
  if (!slug) return null;
  return SUBJECT_DETAILS_MAP[slug] || null;
}

export const ALL_SUBJECT_SLUGS = Object.keys(SUBJECT_DETAILS_MAP);
