export const INITIAL_ASSIGNMENTS = [
  {
    id: "asg-1",
    subject: "Web Development",
    title: "Build a Responsive Portfolio Website",
    description:
      "Create a personal portfolio website using Next.js with responsive design, including a projects section, about section and contact form.",
    tags: ["Next.js", "React", "Tailwind CSS", "Portfolio"],
    status: "pending",
    dueStatus: "Due in 2 days",
    dueDate: "18 Aug 2025, 11:59 PM",
    marks: 10,
    priority: "High Priority",
    urgency: "urgent", // soft red
    priorityType: "high", // green/teal
    icon: "code",
  },
  {
    id: "asg-2",
    subject: "Data Structures & Algorithms",
    title: "Implement Binary Search Tree",
    description:
      "Write a program to implement a Binary Search Tree with insert, delete, search and traversal operations.",
    tags: ["DSA", "C++", "Trees"],
    status: "pending",
    dueStatus: "Due in 4 days",
    dueDate: "20 Aug 2025, 11:59 PM",
    marks: 8,
    priority: "Medium Priority",
    urgency: "upcoming", // soft peach/orange
    priorityType: "medium", // yellow/amber
    icon: "tree",
  },
  {
    id: "asg-3",
    subject: "Database Management Systems",
    title: "Design ER Diagram for College Management System",
    description:
      "Create an ER diagram for the college management system with all relevant entities, attributes and relationships.",
    tags: ["ER Diagram", "Database", "Normalization"],
    status: "pending",
    dueStatus: "Due in 6 days",
    dueDate: "22 Aug 2025, 11:59 PM",
    marks: 10,
    priority: "Medium Priority",
    urgency: "upcoming",
    priorityType: "medium",
    icon: "database",
  },
  {
    id: "asg-4",
    subject: "Computer Networks Lab",
    title: "Configure and Test Network Connectivity",
    description:
      "Configure a small network topology and demonstrate connectivity using ping and traceroute commands.",
    tags: ["Networking", "Cisco", "Lab"],
    status: "submitted",
    dueStatus: "Due in 1 week",
    dueDate: "26 Aug 2025, 11:59 PM",
    marks: 15,
    priority: "Lab",
    urgency: "later", // soft blue
    priorityType: "lab", // soft blue
    icon: "network",
  },
  {
    id: "asg-5",
    subject: "Web Development",
    title: "JavaScript DOM Manipulation Assignment",
    description:
      "Implement a small web app that uses DOM manipulation to add, delete and edit elements dynamically.",
    tags: ["JavaScript", "DOM", "Frontend"],
    status: "submitted",
    dueStatus: "Due in 1 week",
    dueDate: "28 Aug 2025, 11:59 PM",
    marks: 8,
    priority: "Low Priority",
    urgency: "later",
    priorityType: "low", // mint/green
    icon: "code",
  },
  {
    id: "asg-6",
    subject: "Data Structures & Algorithms",
    title: "Graph Algorithms - Short Questions",
    description:
      "Solve the given set of short questions on BFS, DFS, Dijkstra and Topological Sort.",
    tags: ["DSA", "Graphs", "Algorithms"],
    status: "submitted",
    dueStatus: "Due in 10 days",
    dueDate: "01 Sep 2025, 11:59 PM",
    marks: 10,
    priority: "Medium Priority",
    urgency: "later",
    priorityType: "medium",
    icon: "network",
  },
  // Additional assignments to accurately fulfill the 16 Total, 13 Submitted, 2 Overdue stats
  {
    id: "asg-7",
    subject: "Operating Systems",
    title: "Process Scheduling Algorithms Simulator",
    description: "Implement FCFS, SJF, and Round Robin scheduling simulation in C.",
    tags: ["OS", "C", "Algorithms"],
    status: "overdue",
    dueStatus: "Overdue by 3 days",
    dueDate: "14 Aug 2025, 11:59 PM",
    marks: 10,
    priority: "High Priority",
    urgency: "overdue",
    priorityType: "high",
    icon: "terminal",
  },
  {
    id: "asg-8",
    subject: "Software Engineering",
    title: "SRS Document for Healthcare App",
    description: "Write IEEE 830 compliant Software Requirements Specification.",
    tags: ["SRS", "Documentation", "Agile"],
    status: "overdue",
    dueStatus: "Overdue by 5 days",
    dueDate: "12 Aug 2025, 11:59 PM",
    marks: 10,
    priority: "Medium Priority",
    urgency: "overdue",
    priorityType: "medium",
    icon: "file",
  },
  {
    id: "asg-9",
    subject: "Web Development",
    title: "CSS Grid & Flexbox Masterclass",
    description: "Design 3 responsive layout wireframes without CSS frameworks.",
    tags: ["CSS", "Responsive", "UI"],
    status: "submitted",
    dueStatus: "Submitted",
    dueDate: "08 Aug 2025, 11:59 PM",
    marks: 10,
    priority: "Low Priority",
    urgency: "submitted",
    priorityType: "low",
    icon: "code",
  },
  {
    id: "asg-10",
    subject: "Database Management Systems",
    title: "SQL Query Optimization Case Study",
    description: "Analyze query execution plans and create optimal B-Tree indexes.",
    tags: ["SQL", "Postgres", "Performance"],
    status: "submitted",
    dueStatus: "Submitted",
    dueDate: "05 Aug 2025, 11:59 PM",
    marks: 10,
    priority: "Medium Priority",
    urgency: "submitted",
    priorityType: "medium",
    icon: "database",
  },
  {
    id: "asg-11",
    subject: "Computer Networks Lab",
    title: "Wireshark Packet Analysis Lab",
    description: "Capture and analyze TCP 3-way handshake and HTTP/HTTPS packets.",
    tags: ["Wireshark", "TCP/IP", "Security"],
    status: "submitted",
    dueStatus: "Submitted",
    dueDate: "01 Aug 2025, 11:59 PM",
    marks: 15,
    priority: "Lab",
    urgency: "submitted",
    priorityType: "lab",
    icon: "network",
  },
  {
    id: "asg-12",
    subject: "Data Structures & Algorithms",
    title: "Dynamic Programming Challenge Set",
    description: "Solve 0/1 Knapsack, Longest Common Subsequence, and Matrix Chain.",
    tags: ["DP", "Optimization", "Recursion"],
    status: "submitted",
    dueStatus: "Submitted",
    dueDate: "28 Jul 2025, 11:59 PM",
    marks: 10,
    priority: "High Priority",
    urgency: "submitted",
    priorityType: "high",
    icon: "tree",
  },
  {
    id: "asg-13",
    subject: "Cloud Computing",
    title: "Deploy Microservice on Docker",
    description: "Containerize Node.js API with Multi-stage Dockerfile.",
    tags: ["Docker", "DevOps", "Microservices"],
    status: "submitted",
    dueStatus: "Submitted",
    dueDate: "25 Jul 2025, 11:59 PM",
    marks: 10,
    priority: "Medium Priority",
    urgency: "submitted",
    priorityType: "medium",
    icon: "terminal",
  },
  {
    id: "asg-14",
    subject: "Artificial Intelligence",
    title: "A* Search Algorithm Implementation",
    description: "Solve 8-puzzle problem using heuristic Manhattan distance.",
    tags: ["AI", "Heuristics", "Python"],
    status: "submitted",
    dueStatus: "Submitted",
    dueDate: "20 Jul 2025, 11:59 PM",
    marks: 10,
    priority: "High Priority",
    urgency: "submitted",
    priorityType: "high",
    icon: "code",
  },
  {
    id: "asg-15",
    subject: "Cyber Security",
    title: "RSA Encryption & Decryption Lab",
    description: "Demonstrate asymmetric key generation and message signing.",
    tags: ["Crypto", "Security", "RSA"],
    status: "submitted",
    dueStatus: "Submitted",
    dueDate: "15 Jul 2025, 11:59 PM",
    marks: 15,
    priority: "Lab",
    urgency: "submitted",
    priorityType: "lab",
    icon: "terminal",
  },
  {
    id: "asg-16",
    subject: "Open Elective",
    title: "Green Energy & Smart Grids Essay",
    description: "Write a 1500-word essay on IoT applications in microgrids.",
    tags: ["Energy", "IoT", "Sustainability"],
    status: "submitted",
    dueStatus: "Submitted",
    dueDate: "10 Jul 2025, 11:59 PM",
    marks: 10,
    priority: "Low Priority",
    urgency: "submitted",
    priorityType: "low",
    icon: "file",
  },
];

export const UPCOMING_DEADLINES = [
  {
    id: "ud-1",
    title: "Build a Responsive Portfolio Website",
    dueText: "18 Aug 2025 • 2 days left",
    priority: "High",
    priorityType: "high",
  },
  {
    id: "ud-2",
    title: "Implement Binary Search Tree",
    dueText: "20 Aug 2025 • 4 days left",
    priority: "Medium",
    priorityType: "medium",
  },
  {
    id: "ud-3",
    title: "Design ER Diagram",
    dueText: "22 Aug 2025 • 6 days left",
    priority: "Medium",
    priorityType: "medium",
  },
  {
    id: "ud-4",
    title: "Configure Network Connectivity",
    dueText: "26 Aug 2025 • 1 week left",
    priority: "Lab",
    priorityType: "lab",
  },
];

export const SUBMISSION_STATS = {
  completionPercentage: 81,
  submittedCount: 13,
  totalCount: 16,
  overdueCount: 2,
  pendingCount: 3,
};

export const SUBJECTS_LIST = [
  "All Subjects",
  "Web Development",
  "Data Structures & Algorithms",
  "Database Management Systems",
  "Computer Networks Lab",
  "Operating Systems",
];

export const ALL_ASSIGNMENTS = INITIAL_ASSIGNMENTS;

