export const FONT_OPTIONS = [
  {
    id: "inter",
    name: "Inter",
    family: "'Inter', sans-serif",
    category: "Neo-grotesque",
    description: "Modern SaaS standard, crisp micro-legibility in dense dashboards.",
  },
  {
    id: "manrope",
    name: "Manrope",
    family: "'Manrope', sans-serif",
    category: "Geometric Sans",
    description: "Contemporary semi-rounded geometry. Friendly, tech-forward, and premium.",
  },
  {
    id: "plus-jakarta-sans",
    name: "Plus Jakarta Sans",
    family: "'Plus Jakarta Sans', sans-serif",
    category: "Geometric Display",
    description: "Modern geometric typography with distinctive curved terminals.",
  },
  {
    id: "dm-sans",
    name: "DM Sans",
    family: "'DM Sans', sans-serif",
    category: "Low-contrast Geometric",
    description: "Compact geometric sans-serif that excels in tight data grids & metrics.",
  },
  {
    id: "poppins",
    name: "Poppins",
    family: "'Poppins', sans-serif",
    category: "Geometric Display",
    description: "Inviting circular geometry. Welcoming, youthful academic energy.",
  },
  {
    id: "outfit",
    name: "Outfit",
    family: "'Outfit', sans-serif",
    category: "Modern Geometric",
    description: "Warm geometric proportions inspired by modern digital brands.",
  },
  {
    id: "nunito-sans",
    name: "Nunito Sans",
    family: "'Nunito Sans', sans-serif",
    category: "Humanist Sans",
    description: "Softened terminals, balanced proportions. Gentle for long reading.",
  },
  {
    id: "geist",
    name: "Geist",
    family: "'Geist', sans-serif",
    category: "Technical Swiss Sans",
    description: "Precision-engineered Swiss typography designed for modern web apps.",
  },
  {
    id: "roboto",
    name: "Roboto",
    family: "'Roboto', sans-serif",
    category: "Neo-grotesque",
    description: "Google's classic UI typeface with structured geometric forms.",
  },
  {
    id: "source-sans-3",
    name: "Source Sans 3",
    family: "'Source Sans 3', sans-serif",
    category: "Humanist Sans",
    description: "Adobe's open UI workhorse. Exceptional clarity for data tables.",
  },
  {
    id: "ibm-plex-sans",
    name: "IBM Plex Sans",
    family: "'IBM Plex Sans', sans-serif",
    category: "Corporate Technical",
    description: "Industrial yet humanistic grotesque. Conveys authority and discipline.",
  },
  {
    id: "work-sans",
    name: "Work Sans",
    family: "'Work Sans', sans-serif",
    category: "Early Grotesque",
    description: "Charismatic grotesque simplified for modern screen ergonomics.",
  },
];
